
  content: "\e139";
}
#vlocity .glyphicon-fullscreen:before {
  content: "\e140";
}
#vlocity .glyphicon-dashboard:before {
  content: "\e141";
}
#vlocity .glyphicon-paperclip:before {
  content: "\e142";
}
#vlocity .glyphicon-heart-empty:before {
  content: "\e143";
}
#vlocity .glyphicon-link:before {
  content: "\e144";
}
#vlocity .glyphicon-phone:before {
  content: "\e145";
}
#vlocity .glyphicon-pushpin:before {
  content: "\e146";
}
#vlocity .glyphicon-usd:before {
  content: "\e148";
}
#vlocity .glyphicon-gbp:before {
  content: "\e149";
}
#vlocity .glyphicon-sort:before {
  content: "\e150";
}
#vlocity .glyphicon-sort-by-alphabet:before {
  content: "\e151";
}
#vlocity .glyphicon-sort-by-alphabet-alt:before {
  content: "\e152";
}
#vlocity .glyphicon-sort-by-order:before {
  content: "\e153";
}
#vlocity .glyphicon-sort-by-order-alt:before {
  content: "\e154";
}
#vlocity .glyphicon-sort-by-attributes:before {
  content: "\e155";
}
#vlocity .glyphicon-sort-by-attributes-alt:before {
  content: "\e156";
}
#vlocity .glyphicon-unchecked:before {
  content: "\e157";
}
#vlocity .glyphicon-expand:before {
  content: "\e158";
}
#vlocity .glyphicon-collapse-down:before {
  content: "\e159";
}
#vlocity .glyphicon-collapse-up:before {
  content: "\e160";
}
#vlocity .glyphicon-log-in:before {
  content: "\e161";
}
#vlocity .glyphicon-flash:before {
  content: "\e162";
}
#vlocity .glyphicon-log-out:before {
  content: "\e163";
}
#vlocity .glyphicon-new-window:before {
  content: "\e164";
}
#vlocity .glyphicon-record:before {
  content: "\e165";
}
#vlocity .glyphicon-save:before {
  content: "\e166";
}
#vlocity .glyphicon-open:before {
  content: "\e167";
}
#vlocity .glyphicon-saved:before {
  content: "\e168";
}
#vlocity .glyphicon-import:before {
  content: "\e169";
}
#vlocity .glyphicon-export:before {
  content: "\e170";
}
#vlocity .glyphicon-send:before {
  content: "\e171";
}
#vlocity .glyphicon-floppy-disk:before {
  content: "\e172";
}
#vlocity .glyphicon-floppy-saved:before {
  content: "\e173";
}
#vlocity .glyphicon-floppy-remove:before {
  content: "\e174";
}
#vlocity .glyphicon-floppy-save:before {
  content: "\e175";
}
#vlocity .glyphicon-floppy-open:before {
  content: "\e176";
}
#vlocity .glyphicon-credit-card:before {
  content: "\e177";
}
#vlocity .glyphicon-transfer:before {
  content: "\e178";
}
#vlocity .glyphicon-cutlery:before {
  content: "\e179";
}
#vlocity .glyphicon-header:before {
  content: "\e180";
}
#vlocity .glyphicon-compressed:before {
  content: "\e181";
}
#vlocity .glyphicon-earphone:before {
  content: "\e182";
}
#vlocity .glyphicon-phone-alt:before {
  content: "\e183";
}
#vlocity .glyphicon-tower:before {
  content: "\e184";
}
#vlocity .glyphicon-stats:before {
  content: "\e185";
}
#vlocity .glyphicon-sd-video:before {
  content: "\e186";
}
#vlocity .glyphicon-hd-video:before {
  content: "\e187";
}
#vlocity .glyphicon-subtitles:before {
  content: "\e188";
}
#vlocity .glyphicon-sound-stereo:before {
  content: "\e189";
}
#vlocity .glyphicon-sound-dolby:before {
  content: "\e190";
}
#vlocity .glyphicon-sound-5-1:before {
  content: "\e191";
}
#vlocity .glyphicon-sound-6-1:before {
  content: "\e192";
}
#vlocity .glyphicon-sound-7-1:before {
  content: "\e193";
}
#vlocity .glyphicon-copyright-mark:before {
  content: "\e194";
}
#vlocity .glyphicon-registration-mark:before {
  content: "\e195";
}
#vlocity .glyphicon-cloud-download:before {
  content: "\e197";
}
#vlocity .glyphicon-cloud-upload:before {
  content: "\e198";
}
#vlocity .glyphicon-tree-conifer:before {
  content: "\e199";
}
#vlocity .glyphicon-tree-deciduous:before {
  content: "\e200";
}
#vlocity * {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
#vlocity *:before,
#vlocity *:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
#vlocity html {
  font-size: 10px;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
#vlocity body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}
#vlocity input,
#vlocity button,
#vlocity select,
#vlocity textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
#vlocity a {
  color: #337ab7;
  text-decoration: none;
}
#vlocity a:hover,
#vlocity a:focus {
  color: #23527c;
  text-decoration: underline;
}
#vlocity a:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
#vlocity figure {
  margin: 0;
}
#vlocity img {
  vertical-align: middle;
}
#vlocity .img-responsive,
#vlocity .thumbnail > img,
#vlocity .thumbnail a > img,
#vlocity .carousel-inner > .item > img,
#vlocity .carousel-inner > .item > a > img {
  display: block;
  max-width: 100%;
  height: auto;
}
#vlocity .img-rounded {
  border-radius: 6px;
}
#vlocity .img-thumbnail {
  display: inline-block;
  max-width: 100%;
  height: auto;
  padding: 4px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: all 0.2s ease-in-out;
  -o-transition: all 0.2s ease-in-out;
  transition: all 0.2s ease-in-out;
}
#vlocity .img-circle {
  border-radius: 50%;
}
#vlocity hr {
  margin-top: 20px;
  margin-bottom: 20px;
  border: 0;
  border-top: 1px solid #eee;
}
#vlocity .sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
#vlocity .sr-only-focusable:active,
#vlocity .sr-only-focusable:focus {
  position: static;
  width: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  clip: auto;
}
#vlocity h1,
#vlocity h2,
#vlocity h3,
#vlocity h4,
#vlocity h5,
#vlocity h6,
#vlocity .h1,
#vlocity .h2,
#vlocity .h3,
#vlocity .h4,
#vlocity .h5,
#vlocity .h6 {
  font-family: inherit;
  font-weight: 500;
  line-height: 1.1;
  color: inherit;
}
#vlocity h1 small,
#vlocity h2 small,
#vlocity h3 small,
#vlocity h4 small,
#vlocity h5 small,
#vlocity h6 small,
#vlocity .h1 small,
#vlocity .h2 small,
#vlocity .h3 small,
#vlocity .h4 small,
#vlocity .h5 small,
#vlocity .h6 small,
#vlocity h1 .small,
#vlocity h2 .small,
#vlocity h3 .small,
#vlocity h4 .small,
#vlocity h5 .small,
#vlocity h6 .small,
#vlocity .h1 .small,
#vlocity .h2 .small,
#vlocity .h3 .small,
#vlocity .h4 .small,
#vlocity .h5 .small,
#vlocity .h6 .small {
  font-weight: normal;
  line-height: 1;
  color: #777;
}
#vlocity h1,
#vlocity .h1,
#vlocity h2,
#vlocity .h2,
#vlocity h3,
#vlocity .h3 {
  margin-top: 20px;
  margin-bottom: 10px;
}
#vlocity h1 small,
#vlocity .h1 small,
#vlocity h2 small,
#vlocity .h2 small,
#vlocity h3 small,
#vlocity .h3 small,
#vlocity h1 .small,
#vlocity .h1 .small,
#vlocity h2 .small,
#vlocity .h2 .small,
#vlocity h3 .small,
#vlocity .h3 .small {
  font-size: 65%;
}
#vlocity h4,
#vlocity .h4,
#vlocity h5,
#vlocity .h5,
#vlocity h6,
#vlocity .h6 {
  margin-top: 10px;
  margin-bottom: 10px;
}
#vlocity h4 small,
#vlocity .h4 small,
#vlocity h5 small,
#vlocity .h5 small,
#vlocity h6 small,
#vlocity .h6 small,
#vlocity h4 .small,
#vlocity .h4 .small,
#vlocity h5 .small,
#vlocity .h5 .small,
#vlocity h6 .small,
#vlocity .h6 .small {
  font-size: 75%;
}
#vlocity h1,
#vlocity .h1 {
  font-size: 36px;
}
#vlocity h2,
#vlocity .h2 {
  font-size: 30px;
}
#vlocity h3,
#vlocity .h3 {
  font-size: 24px;
}
#vlocity h4,
#vlocity .h4 {
  font-size: 18px;
}
#vlocity h5,
#vlocity .h5 {
  font-size: 14px;
}
#vlocity h6,
#vlocity .h6 {
  font-size: 12px;
}
#vlocity p {
  margin: 0 0 25px;
}
#vlocity .lead {
  margin-bottom: 20px;
  font-size: 16px;
  font-weight: 300;
  line-height: 1.4;
}
@media (min-width: 768px) {
  #vlocity .lead {
    font-size: 21px;
  }
}
#vlocity small,
#vlocity .small {
  font-size: 85%;
}
#vlocity mark,
#vlocity .mark {
  padding: .2em;
  background-color: #fcf8e3;
}
#vlocity .text-left {
  text-align: left;
}
#vlocity .text-right {
  text-align: right;
}
#vlocity .text-center {
  text-align: center;
}
#vlocity .text-justify {
  text-align: justify;
}
#vlocity .text-nowrap {
  white-space: nowrap;
}
#vlocity .text-lowercase {
  text-transform: lowercase;
}
#vlocity .text-uppercase {
  text-transform: uppercase;
}
#vlocity .text-capitalize {
  text-transform: capitalize;
}
#vlocity .text-muted {
  color: #777;
}
#vlocity .text-primary {
  color: #337ab7;
}
#vlocity a.text-primary:hover {
  color: #286090;
}
#vlocity .text-success {
  color: #3c763d;
}
#vlocity a.text-success:hover {
  color: #2b542c;
}
#vlocity .text-info {
  color: #31708f;
}
#vlocity a.text-info:hover {
  color: #245269;
}
#vlocity .text-warning {
  color: #8a6d3b;
}
#vlocity a.text-warning:hover {
  color: #66512c;
}
#vlocity .text-danger {
  color: #a94442;
}
#vlocity a.text-danger:hover {
  color: #843534;
}
#vlocity .bg-primary {
  color: #fff;
  background-color: #337ab7;
}
#vlocity a.bg-primary:hover {
  background-color: #286090;
}
#vlocity .bg-success {
  background-color: #dff0d8;
}
#vlocity a.bg-success:hover {
  background-color: #c1e2b3;
}
#vlocity .bg-info {
  background-color: #d9edf7;
}
#vlocity a.bg-info:hover {
  background-color: #afd9ee;
}
#vlocity .bg-warning {
  background-color: #fcf8e3;
}
#vlocity a.bg-warning:hover {
  background-color: #f7ecb5;
}
#vlocity .bg-danger {
  background-color: #f2dede;
}
#vlocity a.bg-danger:hover {
  background-color: #e4b9b9;
}
#vlocity .page-header {
  padding-bottom: 9px;
  margin: 40px 0 20px;
  border-bottom: 1px solid #eee;
}
#vlocity ul,
#vlocity ol {
  margin-top: 0;
  margin-bottom: 10px;
}
#vlocity ul ul,
#vlocity ol ul,
#vlocity ul ol,
#vlocity ol ol {
  margin-bottom: 0;
}
#vlocity .list-unstyled {
  padding-left: 0;
  list-style: none;
}
#vlocity .list-inline {
  padding-left: 0;
  margin-left: -5px;
  list-style: none;
}
#vlocity .list-inline > li {
  display: inline-block;
  padding-right: 5px;
  padding-left: 5px;
}
#vlocity dl {
  margin-top: 0;
  margin-bottom: 20px;
}
#vlocity dt,
#vlocity dd {
  line-height: 1.42857143;
}
#vlocity dt {
  font-weight: bold;
}
#vlocity dd {
  margin-left: 0;
}
@media (min-width: 768px) {
  #vlocity .dl-horizontal dt {
    float: left;
    width: 160px;
    overflow: hidden;
    clear: left;
    text-align: right;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  #vlocity .dl-horizontal dd {
    margin-left: 180px;
  }
}
#vlocity abbr[title],
#vlocity abbr[data-original-title] {
  cursor: help;
  border-bottom: 1px dotted #777;
}
#vlocity .initialism {
  font-size: 90%;
  text-transform: uppercase;
}
#vlocity blockquote {
  padding: 10px 20px;
  margin: 0 0 20px;
  font-size: 17.5px;
  border-left: 5px solid #eee;
}
#vlocity blockquote p:last-child,
#vlocity blockquote ul:last-child,
#vlocity blockquote ol:last-child {
  margin-bottom: 0;
}
#vlocity blockquote footer,
#vlocity blockquote small,
#vlocity blockquote .small {
  display: block;
  font-size: 80%;
  line-height: 1.42857143;
  color: #777;
}
#vlocity blockquote footer:before,
#vlocity blockquote small:before,
#vlocity blockquote .small:before {
  content: '\2014 \00A0';
}
#vlocity .blockquote-reverse,
#vlocity blockquote.pull-right {
  padding-right: 15px;
  padding-left: 0;
  text-align: right;
  border-right: 5px solid #eee;
  border-left: 0;
}
#vlocity .blockquote-reverse footer:before,
#vlocity blockquote.pull-right footer:before,
#vlocity .blockquote-reverse small:before,
#vlocity blockquote.pull-right small:before,
#vlocity .blockquote-reverse .small:before,
#vlocity blockquote.pull-right .small:before {
  content: '';
}
#vlocity .blockquote-reverse footer:after,
#vlocity blockquote.pull-right footer:after,
#vlocity .blockquote-reverse small:after,
#vlocity blockquote.pull-right small:after,
#vlocity .blockquote-reverse .small:after,
#vlocity blockquote.pull-right .small:after {
  content: '\00A0 \2014';
}
#vlocity address {
  margin-bottom: 20px;
  font-style: normal;
  line-height: 1.42857143;
}
#vlocity code,
#vlocity kbd,
#vlocity pre,
#vlocity samp {
  font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
}
#vlocity code {
  padding: 2px 4px;
  font-size: 90%;
  color: #c7254e;
  background-color: #f9f2f4;
  border-radius: 4px;
}
#vlocity kbd {
  padding: 2px 4px;
  font-size: 90%;
  color: #fff;
  background-color: #333;
  border-radius: 3px;
  -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.25);
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.25);
}
#vlocity kbd kbd {
  padding: 0;
  font-size: 100%;
  font-weight: bold;
  -webkit-box-shadow: none;
  box-shadow: none;
}
#vlocity pre {
  display: block;
  padding: 9.5px;
  margin: 0 0 10px;
  font-size: 13px;
  line-height: 1.42857143;
  color: #333;
  word-break: break-all;
  word-wrap: break-word;
  background-color: #f5f5f5;
  border: 1px solid #ccc;
  border-radius: 4px;
}
#vlocity pre code {
  padding: 0;
  font-size: inherit;
  color: inherit;
  white-space: pre-wrap;
  background-color: transparent;
  border-radius: 0;
}
#vlocity .pre-scrollable {
  max-height: 340px;
  overflow-y: scroll;
}
#vlocity .container {
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
@media (min-width: 768px) {
  #vlocity .container {
    width: 750px;
  }
}
@media (min-width: 992px) {
  #vlocity .container {
    width: 970px;
  }
}
@media (min-width: 1200px) {
  #vlocity .container {
    width: 1170px;
  }
}
#vlocity .container-fluid {
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
/*#vlocity .row {
  margin-right: -15px;
  margin-left: -15px;
}*/
#vlocity .col-xs-1,
#vlocity .col-sm-1,
#vlocity .col-md-1,
#vlocity .col-lg-1,
#vlocity .col-xs-2,
#vlocity .col-sm-2,
#vlocity .col-md-2,
#vlocity .col-lg-2,
#vlocity .col-xs-3,
#vlocity .col-sm-3,
#vlocity .col-md-3,
#vlocity .col-lg-3,
#vlocity .col-xs-4,
#vlocity .col-sm-4,
#vlocity .col-md-4,
#vlocity .col-lg-4,
#vlocity .col-xs-5,
#vlocity .col-sm-5,
#vlocity .col-md-5,
#vlocity .col-lg-5,
#vlocity .col-xs-6,
#vlocity .col-sm-6,
#vlocity .col-md-6,
#vlocity .col-lg-6,
#vlocity .col-xs-7,
#vlocity .col-sm-7,
#vlocity .col-md-7,
#vlocity .col-lg-7,
#vlocity .col-xs-8,
#vlocity .col-sm-8,
#vlocity .col-md-8,
#vlocity .col-lg-8,
#vlocity .col-xs-9,
#vlocity .col-sm-9,
#vlocity .col-md-9,
#vlocity .col-lg-9,
#vlocity .col-xs-10,
#vlocity .col-sm-10,
#vlocity .col-md-10,
#vlocity .col-lg-10,
#vlocity .col-xs-11,
#vlocity .col-sm-11,
#vlocity .col-md-11,
#vlocity .col-lg-11,
#vlocity .col-xs-12,
#vlocity .col-sm-12,
#vlocity .col-md-12,
#vlocity .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
#vlocity .col-xs-1,
#vlocity .col-xs-2,
#vlocity .col-xs-3,
#vlocity .col-xs-4,
#vlocity .col-xs-5,
#vlocity .col-xs-6,
#vlocity .col-xs-7,
#vlocity .col-xs-8,
#vlocity .col-xs-9,
#vlocity .col-xs-10,
#vlocity .col-xs-11,
#vlocity .col-xs-12 {
  float: left;
}
#vlocity .col-xs-12 {
  width: 100%;
}
#vlocity .col-xs-11 {
  width: 91.66666667%;
}
#vlocity .col-xs-10 {
  width: 83.33333333%;
}
#vlocity .col-xs-9 {
  width: 75%;
}
#vlocity .col-xs-8 {
  width: 66.66666667%;
}
#vlocity .col-xs-7 {
  width: 58.33333333%;
}
#vlocity .col-xs-6 {
  width: 50%;
}
#vlocity .col-xs-5 {
  width: 41.66666667%;
}
#vlocity .col-xs-4 {
  width: 33.33333333%;
}
#vlocity .col-xs-3 {
  width: 25%;
}
#vlocity .col-xs-2 {
  width: 16.66666667%;
}
#vlocity .col-xs-1 {
  width: 8.33333333%;
}
#vlocity .col-xs-pull-12 {
  right: 100%;
}
#vlocity .col-xs-pull-11 {
  right: 91.66666667%;
}
#vlocity .col-xs-pull-10 {
  right: 83.33333333%;
}
#vlocity .col-xs-pull-9 {
  right: 75%;
}
#vlocity .col-xs-pull-8 {
  right: 66.66666667%;
}
#vlocity .col-xs-pull-7 {
  right: 58.33333333%;
}
#vlocity .col-xs-pull-6 {
  right: 50%;
}
#vlocity .col-xs-pull-5 {
  right: 41.66666667%;
}
#vlocity .col-xs-pull-4 {
  right: 33.33333333%;
}
#vlocity .col-xs-pull-3 {
  right: 25%;
}
#vlocity .col-xs-pull-2 {
  right: 16.66666667%;
}
#vlocity .col-xs-pull-1 {
  right: 8.33333333%;
}
#vlocity .col-xs-pull-0 {
  right: auto;
}
#vlocity .col-xs-push-12 {
  left: 100%;
}
#vlocity .col-xs-push-11 {
  left: 91.66666667%;
}
#vlocity .col-xs-push-10 {
  left: 83.33333333%;
}
#vlocity .col-xs-push-9 {
  left: 75%;
}
#vlocity .col-xs-push-8 {
  left: 66.66666667%;
}
#vlocity .col-xs-push-7 {
  left: 58.33333333%;
}
#vlocity .col-xs-push-6 {
  left: 50%;
}
#vlocity .col-xs-push-5 {
  left: 41.66666667%;
}
#vlocity .col-xs-push-4 {
  left: 33.33333333%;
}
#vlocity .col-xs-push-3 {
  left: 25%;
}
#vlocity .col-xs-push-2 {
  left: 16.66666667%;
}
#vlocity .col-xs-push-1 {
  left: 8.33333333%;
}
#vlocity .col-xs-push-0 {
  left: auto;
}
#vlocity .col-xs-offset-12 {
  margin-left: 100%;
}
#vlocity .col-xs-offset-11 {
  margin-left: 91.66666667%;
}
#vlocity .col-xs-offset-10 {
  margin-left: 83.33333333%;
}
#vlocity .col-xs-offset-9 {
  margin-left: 75%;
}
#vlocity .col-xs-offset-8 {
  margin-left: 66.66666667%;
}
#vlocity .col-xs-offset-7 {
  margin-left: 58.33333333%;
}
#vlocity .col-xs-offset-6 {
  margin-left: 50%;
}
#vlocity .col-xs-offset-5 {
  margin-left: 41.66666667%;
}
#vlocity .col-xs-offset-4 {
  margin-left: 33.33333333%;
}
#vlocity .col-xs-offset-3 {
  margin-left: 25%;
}
#vlocity .col-xs-offset-2 {
  margin-left: 16.66666667%;
}
#vlocity .col-xs-offset-1 {
  margin-left: 8.33333333%;
}
#vlocity .col-xs-offset-0 {
  margin-left: 0;
}
@media (min-width: 768px) {
  #vlocity .col-sm-1,
  #vlocity .col-sm-2,
  #vlocity .col-sm-3,
  #vlocity .col-sm-4,
  #vlocity .col-sm-5,
  #vlocity .col-sm-6,
  #vlocity .col-sm-7,
  #vlocity .col-sm-8,
  #vlocity .col-sm-9,
  #vlocity .col-sm-10,
  #vlocity .col-sm-11,
  #vlocity .col-sm-12 {
    float: left;
  }
  #vlocity .col-sm-12 {
    width: 100%;
  }
  #vlocity .col-sm-11 {
    width: 91.66666667%;
  }
  #vlocity .col-sm-10 {
    width: 83.33333333%;
  }
  #vlocity .col-sm-9 {
    width: 75%;
  }
  #vlocity .col-sm-8 {
    width: 66.66666667%;
  }
  #vlocity .col-sm-7 {
    width: 58.33333333%;
  }
  #vlocity .col-sm-6 {
    width: 50%;
  }
  #vlocity .col-sm-5 {
    width: 41.66666667%;
  }
  #vlocity .col-sm-4 {
    width: 33.33333333%;
  }
  #vlocity .col-sm-3 {
    width: 25%;
  }
  #vlocity .col-sm-2 {
    width: 16.66666667%;
  }
  #vlocity .col-sm-1 {
    width: 8.33333333%;
  }
  #vlocity .col-sm-pull-12 {
    right: 100%;
  }
  #vlocity .col-sm-pull-11 {
    right: 91.66666667%;
  }
  #vlocity .col-sm-pull-10 {
    right: 83.33333333%;
  }
  #vlocity .col-sm-pull-9 {
    right: 75%;
  }
  #vlocity .col-sm-pull-8 {
    right: 66.66666667%;
  }
  #vlocity .col-sm-pull-7 {
    right: 58.33333333%;
  }
  #vlocity .col-sm-pull-6 {
    right: 50%;
  }
  #vlocity .col-sm-pull-5 {
    right: 41.66666667%;
  }
  #vlocity .col-sm-pull-4 {
    right: 33.33333333%;
  }
  #vlocity .col-sm-pull-3 {
    right: 25%;
  }
  #vlocity .col-sm-pull-2 {
    right: 16.66666667%;
  }
  #vlocity .col-sm-pull-1 {
    right: 8.33333333%;
  }
  #vlocity .col-sm-pull-0 {
    right: auto;
  }
  #vlocity .col-sm-push-12 {
    left: 100%;
  }
  #vlocity .col-sm-push-11 {
    left: 91.66666667%;
  }
  #vlocity .col-sm-push-10 {
    left: 83.33333333%;
  }
  #vlocity .col-sm-push-9 {
    left: 75%;
  }
  #vlocity .col-sm-push-8 {
    left: 66.66666667%;
  }
  #vlocity .col-sm-push-7 {
    left: 58.33333333%;
  }
  #vlocity .col-sm-push-6 {
    left: 50%;
  }
  #vlocity .col-sm-push-5 {
    left: 41.66666667%;
  }
  #vlocity .col-sm-push-4 {
    left: 33.33333333%;
  }
  #vlocity .col-sm-push-3 {
    left: 25%;
  }
  #vlocity .col-sm-push-2 {
    left: 16.66666667%;
  }
  #vlocity .col-sm-push-1 {
    left: 8.33333333%;
  }
  #vlocity .col-sm-push-0 {
    left: auto;
  }
  #vlocity .col-sm-offset-12 {
    margin-left: 100%;
  }
  #vlocity .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  #vlocity .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  #vlocity .col-sm-offset-9 {
    margin-left: 75%;
  }
  #vlocity .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  #vlocity .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  #vlocity .col-sm-offset-6 {
    margin-left: 50%;
  }
  #vlocity .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  #vlocity .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  #vlocity .col-sm-offset-3 {
    margin-left: 25%;
  }
  #vlocity .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  #vlocity .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  #vlocity .col-sm-offset-0 {
    margin-left: 0;
  }
}
@media (min-width: 992px) {
  #vlocity .col-md-1,
  #vlocity .col-md-2,
  #vlocity .col-md-3,
  #vlocity .col-md-4,
  #vlocity .col-md-5,
  #vlocity .col-md-6,
  #vlocity .col-md-7,
  #vlocity .col-md-8,
  #vlocity .col-md-9,
  #vlocity .col-md-10,
  #vlocity .col-md-11,
  #vlocity .col-md-12 {
    float: left;
  }
  #vlocity .col-md-12 {
    width: 100%;
  }
  #vlocity .col-md-11 {
    width: 91.66666667%;
  }
  #vlocity .col-md-10 {
    width: 83.33333333%;
  }
  #vlocity .col-md-9 {
    width: 75%;
  }
  #vlocity .col-md-8 {
    width: 66.66666667%;
  }
  #vlocity .col-md-7 {
    width: 58.33333333%;
  }
  #vlocity .col-md-6 {
    width: 50%;
  }
  #vlocity .col-md-5 {
    width: 41.66666667%;
  }
  #vlocity .col-md-4 {
    width: 33.33333333%;
  }
  #vlocity .col-md-3 {
    width: 25%;
  }
  #vlocity .col-md-2 {
    width: 16.66666667%;
  }
  #vlocity .col-md-1 {
    width: 8.33333333%;
  }
  #vlocity .col-md-pull-12 {
    right: 100%;
  }
  #vlocity .col-md-pull-11 {
    right: 91.66666667%;
  }
  #vlocity .col-md-pull-10 {
    right: 83.33333333%;
  }
  #vlocity .col-md-pull-9 {
    right: 75%;
  }
  #vlocity .col-md-pull-8 {
    right: 66.66666667%;
  }
  #vlocity .col-md-pull-7 {
    right: 58.33333333%;
  }
  #vlocity .col-md-pull-6 {
    right: 50%;
  }
  #vlocity .col-md-pull-5 {
    right: 41.66666667%;
  }
  #vlocity .col-md-pull-4 {
    right: 33.33333333%;
  }
  #vlocity .col-md-pull-3 {
    right: 25%;
  }
  #vlocity .col-md-pull-2 {
    right: 16.66666667%;
  }
  #vlocity .col-md-pull-1 {
    right: 8.33333333%;
  }
  #vlocity .col-md-pull-0 {
    right: auto;
  }
  #vlocity .col-md-push-12 {
    left: 100%;
  }
  #vlocity .col-md-push-11 {
    left: 91.66666667%;
  }
  #vlocity .col-md-push-10 {
    left: 83.33333333%;
  }
  #vlocity .col-md-push-9 {
    left: 75%;
  }
  #vlocity .col-md-push-8 {
    left: 66.66666667%;
  }
  #vlocity .col-md-push-7 {
    left: 58.33333333%;
  }
  #vlocity .col-md-push-6 {
    left: 50%;
  }
  #vlocity .col-md-push-5 {
    left: 41.66666667%;
  }
  #vlocity .col-md-push-4 {
    left: 33.33333333%;
  }
  #vlocity .col-md-push-3 {
    left: 25%;
  }
  #vlocity .col-md-push-2 {
    left: 16.66666667%;
  }
  #vlocity .col-md-push-1 {
    left: 8.33333333%;
  }
  #vlocity .col-md-push-0 {
    left: auto;
  }
  #vlocity .col-md-offset-12 {
    margin-left: 100%;
  }
  #vlocity .col-md-offset-11 {
    margin-left: 91.66666667%;
  }
  #vlocity .col-md-offset-10 {
    margin-left: 83.33333333%;
  }
  #vlocity .col-md-offset-9 {
    margin-left: 75%;
  }
  #vlocity .col-md-offset-8 {
    margin-left: 66.66666667%;
  }
  #vlocity .col-md-offset-7 {
    margin-left: 58.33333333%;
  }
  #vlocity .col-md-offset-6 {
    margin-left: 50%;
  }
  #vlocity .col-md-offset-5 {
    margin-left: 41.66666667%;
  }
  #vlocity .col-md-offset-4 {
    margin-left: 33.33333333%;
  }
  #vlocity .col-md-offset-3 {
    margin-left: 25%;
  }
  #vlocity .col-md-offset-2 {
    margin-left: 16.66666667%;
  }
  #vlocity .col-md-offset-1 {
    margin-left: 8.33333333%;
  }
  #vlocity .col-md-offset-0 {
    margin-left: 0;
  }
}
@media (min-width: 1200px) {
  #vlocity .col-lg-1,
  #vlocity .col-lg-2,
  #vlocity .col-lg-3,
  #vlocity .col-lg-4,
  #vlocity .col-lg-5,
  #vlocity .col-lg-6,
  #vlocity .col-lg-7,
  #vlocity .col-lg-8,
  #vlocity .col-lg-9,
  #vlocity .col-lg-10,
  #vlocity .col-lg-11,
  #vlocity .col-lg-12 {
    float: left;
  }
  #vlocity .col-lg-12 {
    width: 100%;
  }
  #vlocity .col-lg-11 {
    width: 91.66666667%;
  }
  #vlocity .col-lg-10 {
    width: 83.33333333%;
  }
  #vlocity .col-lg-9 {
    width: 75%;
  }
  #vlocity .col-lg-8 {
    width: 66.66666667%;
  }
  #vlocity .col-lg-7 {
    width: 58.33333333%;
  }
  #vlocity .col-lg-6 {
    width: 50%;
  }
  #vlocity .col-lg-5 {
    width: 41.66666667%;
  }
  #vlocity .col-lg-4 {
    width: 33.33333333%;
  }
  #vlocity .col-lg-3 {
    width: 25%;
  }
  #vlocity .col-lg-2 {
    width: 16.66666667%;
  }
  #vlocity .col-lg-1 {
    width: 8.33333333%;
  }
  #vlocity .col-lg-pull-12 {
    right: 100%;
  }
  #vlocity .col-lg-pull-11 {
    right: 91.66666667%;
  }
  #vlocity .col-lg-pull-10 {
    right: 83.33333333%;
  }
  #vlocity .col-lg-pull-9 {
    right: 75%;
  }
  #vlocity .col-lg-pull-8 {
    right: 66.66666667%;
  }
  #vlocity .col-lg-pull-7 {
    right: 58.33333333%;
  }
  #vlocity .col-lg-pull-6 {
    right: 50%;
  }
  #vlocity .col-lg-pull-5 {
    right: 41.66666667%;
  }
  #vlocity .col-lg-pull-4 {
    right: 33.33333333%;
  }
  #vlocity .col-lg-pull-3 {
    right: 25%;
  }
  #vlocity .col-lg-pull-2 {
    right: 16.66666667%;
  }
  #vlocity .col-lg-pull-1 {
    right: 8.33333333%;
  }
  #vlocity .col-lg-pull-0 {
    right: auto;
  }
  #vlocity .col-lg-push-12 {
    left: 100%;
  }
  #vlocity .col-lg-push-11 {
    left: 91.66666667%;
  }
  #vlocity .col-lg-push-10 {
    left: 83.33333333%;
  }
  #vlocity .col-lg-push-9 {
    left: 75%;
  }
  #vlocity .col-lg-push-8 {
    left: 66.66666667%;
  }
  #vlocity .col-lg-push-7 {
    left: 58.33333333%;
  }
  #vlocity .col-lg-push-6 {
    left: 50%;
  }
  #vlocity .col-lg-push-5 {
    left: 41.66666667%;
  }
  #vlocity .col-lg-push-4 {
    left: 33.33333333%;
  }
  #vlocity .col-lg-push-3 {
    left: 25%;
  }
  #vlocity .col-lg-push-2 {
    left: 16.66666667%;
  }
  #vlocity .col-lg-push-1 {
    left: 8.33333333%;
  }
  #vlocity .col-lg-push-0 {
    left: auto;
  }
  #vlocity .col-lg-offset-12 {
    margin-left: 100%;
  }
  #vlocity .col-lg-offset-11 {
    margin-left: 91.66666667%;
  }
  #vlocity .col-lg-offset-10 {
    margin-left: 83.33333333%;
  }
  #vlocity .col-lg-offset-9 {
    margin-left: 75%;
  }
  #vlocity .col-lg-offset-8 {
    margin-left: 66.66666667%;
  }
  #vlocity .col-lg-offset-7 {
    margin-left: 58.33333333%;
  }
  #vlocity .col-lg-offset-6 {
    margin-left: 50%;
  }
  #vlocity .col-lg-offset-5 {
    margin-left: 41.66666667%;
  }
  #vlocity .col-lg-offset-4 {
    margin-left: 33.33333333%;
  }
  #vlocity .col-lg-offset-3 {
    margin-left: 25%;
  }
  #vlocity .col-lg-offset-2 {
    margin-left: 16.66666667%;
  }
  #vlocity .col-lg-offset-1 {
    margin-left: 8.33333333%;
  }
  #vlocity .col-lg-offset-0 {
    margin-left: 0;
  }
}
#vlocity table {
  background-color: transparent;
}
#vlocity caption {
  padding-top: 8px;
  padding-bottom: 8px;
  color: #777;
  text-align: left;
}
#vlocity th {
  text-align: left;
}
#vlocity .table {
  width: 100%;
  max-width: 100%;
  margin-bottom: 20px;
}
#vlocity .table > thead > tr > th,
#vlocity .table > tbody > tr > th,
#vlocity .table > tfoot > tr > th,
#vlocity .table > thead > tr > td,
#vlocity .table > tbody > tr > td,
#vlocity .table > tfoot > tr > td {
  padding: 8px;
  line-height: 1.42857143;
  vertical-align: top;
  border-top: 1px solid #ddd;
}
#vlocity .table > thead > tr > th {
  vertical-align: bottom;
  border-bottom: 2px solid #ddd;
}
#vlocity .table > caption + thead > tr:first-child > th,
#vlocity .table > colgroup + thead > tr:first-child > th,
#vlocity .table > thead:first-child > tr:first-child > th,
#vlocity .table > caption + thead > tr:first-child > td,
#vlocity .table > colgroup + thead > tr:first-child > td,
#vlocity .table > thead:first-child > tr:first-child > td {
  border-top: 0;
}
#vlocity .table > tbody + tbody {
  border-top: 2px solid #ddd;
}
#vlocity .table .table {
  background-color: #fff;
}
#vlocity .table-condensed > thead > tr > th,
#vlocity .table-condensed > tbody > tr > th,
#vlocity .table-condensed > tfoot > tr > th,
#vlocity .table-condensed > thead > tr > td,
#vlocity .table-condensed > tbody > tr > td,
#vlocity .table-condensed > tfoot > tr > td {
  padding: 5px;
}
#vlocity .table-bordered {
  border: 1px solid #ddd;
}
#vlocity .table-bordered > thead > tr > th,
#vlocity .table-bordered > tbody > tr > th,
#vlocity .table-bordered > tfoot > tr > th,
#vlocity .table-bordered > thead > tr > td,
#vlocity .table-bordered > tbody > tr > td,
#vlocity .table-bordered > tfoot > tr > td {
  border: 1px solid #ddd;
}
#vlocity .table-bordered > thead > tr > th,
#vlocity .table-bordered > thead > tr > td {
  border-bottom-width: 2px;
}
#vlocity .table-striped > tbody > tr:nth-child(odd) {
  background-color: #f9f9f9;
}
#vlocity .table-hover > tbody > tr:hover {
  background-color: #f5f5f5;
}
#vlocity table col[class*="col-"] {
  position: static;
  display: table-column;
  float: none;
}
#vlocity table td[class*="col-"],
#vlocity table th[class*="col-"] {
  position: static;
  display: table-cell;
  float: none;
}
#vlocity .table > thead > tr > td.active,
#vlocity .table > tbody > tr > td.active,
#vlocity .table > tfoot > tr > td.active,
#vlocity .table > thead > tr > th.active,
#vlocity .table > tbody > tr > th.active,
#vlocity .table > tfoot > tr > th.active,
#vlocity .table > thead > tr.active > td,
#vlocity .table > tbody > tr.active > td,
#vlocity .table > tfoot > tr.active > td,
#vlocity .table > thead > tr.active > th,
#vlocity .table > tbody > tr.active > th,
#vlocity .table > tfoot > tr.active > th {
  background-color: #f5f5f5;
}
#vlocity .table-hover > tbody > tr > td.active:hover,
#vlocity .table-hover > tbody > tr > th.active:hover,
#vlocity .table-hover > tbody > tr.active:hover > td,
#vlocity .table-hover > tbody > tr:hover > .active,
#vlocity .table-hover > tbody > tr.active:hover > th {
  background-color: #e8e8e8;
}
#vlocity .table > thead > tr > td.success,
#vlocity .table > tbody > tr > td.success,
#vlocity .table > tfoot > tr > td.success,
#vlocity .table > thead > tr > th.success,
#vlocity .table > tbody > tr > th.success,
#vlocity .table > tfoot > tr > th.success,
#vlocity .table > thead > tr.success > td,
#vlocity .table > tbody > tr.success > td,
#vlocity .table > tfoot > tr.success > td,
#vlocity .table > thead > tr.success > th,
#vlocity .table > tbody > tr.success > th,
#vlocity .table > tfoot > tr.success > th {
  background-color: #dff0d8;
}
#vlocity .table-hover > tbody > tr > td.success:hover,
#vlocity .table-hover > tbody > tr > th.success:hover,
#vlocity .table-hover > tbody > tr.success:hover > td,
#vlocity .table-hover > tbody > tr:hover > .success,
#vlocity .table-hover > tbody > tr.success:hover > th {
  background-color: #d0e9c6;
}
#vlocity .table > thead > tr > td.info,
#vlocity .table > tbody > tr > td.info,
#vlocity .table > tfoot > tr > td.info,
#vlocity .table > thead > tr > th.info,
#vlocity .table > tbody > tr > th.info,
#vlocity .table > tfoot > tr > th.info,
#vlocity .table > thead > tr.info > td,
#vlocity .table > tbody > tr.info > td,
#vlocity .table > tfoot > tr.info > td,
#vlocity .table > thead > tr.info > th,
#vlocity .table > tbody > tr.info > th,
#vlocity .table > tfoot > tr.info > th {
  background-color: #d9edf7;
}
#vlocity .table-hover > tbody > tr > td.info:hover,
#vlocity .table-hover > tbody > tr > th.info:hover,
#vlocity .table-hover > tbody > tr.info:hover > td,
#vlocity .table-hover > tbody > tr:hover > .info,
#vlocity .table-hover > tbody > tr.info:hover > th {
  background-color: #c4e3f3;
}
#vlocity .table > thead > tr > td.warning,
#vlocity .table > tbody > tr > td.warning,
#vlocity .table > tfoot > tr > td.warning,
#vlocity .table > thead > tr > th.warning,
#vlocity .table > tbody > tr > th.warning,
#vlocity .table > tfoot > tr > th.warning,
#vlocity .table > thead > tr.warning > td,
#vlocity .table > tbody > tr.warning > td,
#vlocity .table > tfoot > tr.warning > td,
#vlocity .table > thead > tr.warning > th,
#vlocity .table > tbody > tr.warning > th,
#vlocity .table > tfoot > tr.warning > th {
  background-color: #fcf8e3;
}
#vlocity .table-hover > tbody > tr > td.warning:hover,
#vlocity .table-hover > tbody > tr > th.warning:hover,
#vlocity .table-hover > tbody > tr.warning:hover > td,
#vlocity .table-hover > tbody > tr:hover > .warning,
#vlocity .table-hover > tbody > tr.warning:hover > th {
  background-color: #faf2cc;
}
#vlocity .table > thead > tr > td.danger,
#vlocity .table > tbody > tr > td.danger,
#vlocity .table > tfoot > tr > td.danger,
#vlocity .table > thead > tr > th.danger,
#vlocity .table > tbody > tr > th.danger,
#vlocity .table > tfoot > tr > th.danger,
#vlocity .table > thead > tr.danger > td,
#vlocity .table > tbody > tr.danger > td,
#vlocity .table > tfoot > tr.danger > td,
#vlocity .table > thead > tr.danger > th,
#vlocity .table > tbody > tr.danger > th,
#vlocity .table > tfoot > tr.danger > th {
  background-color: #f2dede;
}
#vlocity .table-hover > tbody > tr > td.danger:hover,
#vlocity .table-hover > tbody > tr > th.danger:hover,
#vlocity .table-hover > tbody > tr.danger:hover > td,
#vlocity .table-hover > tbody > tr:hover > .danger,
#vlocity .table-hover > tbody > tr.danger:hover > th {
  background-color: #ebcccc;
}
#vlocity .table-responsive {
  min-height: .01%;
  overflow-x: auto;
}
@media screen and (max-width: 767px) {
  #vlocity .table-responsive {
    width: 100%;
    margin-bottom: 15px;
    overflow-y: hidden;
    -ms-overflow-style: -ms-autohiding-scrollbar;
    border: 1px solid #ddd;
  }
  #vlocity .table-responsive > .table {
    margin-bottom: 0;
  }
  #vlocity .table-responsive > .table > thead > tr > th,
  #vlocity .table-responsive > .table > tbody > tr > th,
  #vlocity .table-responsive > .table > tfoot > tr > th,
  #vlocity .table-responsive > .table > thead > tr > td,
  #vlocity .table-responsive > .table > tbody > tr > td,
  #vlocity .table-responsive > .table > tfoot > tr > td {
    white-space: nowrap;
  }
  #vlocity .table-responsive > .table-bordered {
    border: 0;
  }
  #vlocity .table-responsive > .table-bordered > thead > tr > th:first-child,
  #vlocity .table-responsive > .table-bordered > tbody > tr > th:first-child,
  #vlocity .table-responsive > .table-bordered > tfoot > tr > th:first-child,
  #vlocity .table-responsive > .table-bordered > thead > tr > td:first-child,
  #vlocity .table-responsive > .table-bordered > tbody > tr > td:first-child,
  #vlocity .table-responsive > .table-bordered > tfoot > tr > td:first-child {
    border-left: 0;
  }
  #vlocity .table-responsive > .table-bordered > thead > tr > th:last-child,
  #vlocity .table-responsive > .table-bordered > tbody > tr > th:last-child,
  #vlocity .table-responsive > .table-bordered > tfoot > tr > th:last-child,
  #vlocity .table-responsive > .table-bordered > thead > tr > td:last-child,
  #vlocity .table-responsive > .table-bordered > tbody > tr > td:last-child,
  #vlocity .table-responsive > .table-bordered > tfoot > tr > td:last-child {
    border-right: 0;
  }
  #vlocity .table-responsive > .table-bordered > tbody > tr:last-child > th,
  #vlocity .table-responsive > .table-bordered > tfoot > tr:last-child > th,
  #vlocity .table-responsive > .table-bordered > tbody > tr:last-child > td,
  #vlocity .table-responsive > .table-bordered > tfoot > tr:last-child > td {
    border-bottom: 0;
  }
}
#vlocity fieldset {
  min-width: 0;
  padding: 0;
  margin: 0;
  border: 0;
}
#vlocity legend {
  display: block;
  width: 100%;
  padding: 0;
  margin-bottom: 20px;
  font-size: 21px;
  line-height: inherit;
  color: #333;
  border: 0;
  border-bottom: 1px solid #e5e5e5;
}
#vlocity label {
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
  font-weight: bold;
}
#vlocity input[type="search"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
#vlocity input[type="radio"],
#vlocity input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
  line-height: normal;
}
#vlocity input[type="file"] {
  display: block;
}
#vlocity input[type="range"] {
  display: block;
  width: 100%;
}
#vlocity select[multiple],
#vlocity select[size] {
  height: auto;
}
#vlocity input[type="file"]:focus,
#vlocity input[type="radio"]:focus,
#vlocity input[type="checkbox"]:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
#vlocity output {
  display: block;
  padding-top: 7px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
}
#vlocity .form-control {
  display: block;
  width: 100%;
  height: 34px;
  padding: 6px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  -webkit-transition: border-color ease-in-out 0.15s, -webkit-box-shadow ease-in-out 0.15s;
  -o-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
  transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}
#vlocity .form-control:focus {
  border-color: #66afe9;
  outline: 0;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
}
#vlocity .form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
#vlocity .form-control:-ms-input-placeholder {
  color: #999;
}
#vlocity .form-control::-webkit-input-placeholder {
  color: #999;
}
#vlocity .form-control[disabled],
#vlocity .form-control[readonly],
#vlocity fieldset[disabled] .form-control {
  cursor: not-allowed;
  background-color: #eee;
  opacity: 1;
}
#vlocity textarea.form-control {
  height: auto;
}
#vlocity input[type="search"] {
  -webkit-appearance: none;
}
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  #vlocity input[type="date"],
  #vlocity input[type="time"],
  #vlocity input[type="datetime-local"],
  #vlocity input[type="month"] {
    line-height: 34px;
  }
  #vlocity input[type="date"].input-sm,
  #vlocity input[type="time"].input-sm,
  #vlocity input[type="datetime-local"].input-sm,
  #vlocity input[type="month"].input-sm {
    line-height: 30px;
  }
  #vlocity input[type="date"].input-lg,
  #vlocity input[type="time"].input-lg,
  #vlocity input[type="datetime-local"].input-lg,
  #vlocity input[type="month"].input-lg {
    line-height: 46px;
  }
}
#vlocity .form-group {
  margin-bottom: 15px;
}
#vlocity .radio,
#vlocity .checkbox {
  position: static;
  display: block;
  margin-top: 10px;
  margin-bottom: 10px;
}
#vlocity .radio label,
#vlocity .checkbox label {
  min-height: 20px;
  padding-left: 20px;
  margin-bottom: 0;
  font-weight: normal;
  cursor: pointer;
}
#vlocity .radio input[type="radio"],
#vlocity .radio-inline input[type="radio"],
#vlocity .checkbox input[type="checkbox"],
#vlocity .checkbox-inline input[type="checkbox"] {
  /*position: absolute;
  margin-top: 4px \9;
  margin-left: -20px;*/
  margin-right: 5px;
}
#vlocity .radio + .radio,
#vlocity .checkbox + .checkbox {
  margin-top: -5px;
}
#vlocity .radio-inline,
#vlocity .checkbox-inline {
  display: inline-block;
  padding-left: 20px;
  margin-bottom: 0;
  font-weight: normal;
  vertical-align: middle;
  cursor: pointer;
}
#vlocity .radio-inline + .radio-inline,
#vlocity .checkbox-inline + .checkbox-inline {
  margin-top: 0;
  margin-left: 10px;
}
#vlocity input[type="radio"][disabled],
#vlocity input[type="checkbox"][disabled],
#vlocity input[type="radio"].disabled,
#vlocity input[type="checkbox"].disabled,
#vlocity fieldset[disabled] input[type="radio"],
#vlocity fieldset[disabled] input[type="checkbox"] {
  cursor: not-allowed;
}
#vlocity .radio-inline.disabled,
#vlocity .checkbox-inline.disabled,
#vlocity fieldset[disabled] .radio-inline,
#vlocity fieldset[disabled] .checkbox-inline {
  cursor: not-allowed;
}
#vlocity .radio.disabled label,
#vlocity .checkbox.disabled label,
#vlocity fieldset[disabled] .radio label,
#vlocity fieldset[disabled] .checkbox label {
  cursor: not-allowed;
}
#vlocity .form-control-static {
  padding-top: 7px;
  padding-bottom: 7px;
  margin-bottom: 0;
}
#vlocity .form-control-static.input-lg,
#vlocity .form-control-static.input-sm {
  padding-right: 0;
  padding-left: 0;
}
#vlocity .input-sm,
#vlocity .form-group-sm .form-control {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
#vlocity select.input-sm,
#vlocity select.form-group-sm .form-control {
  height: 30px;
  line-height: 30px;
}
#vlocity textarea.input-sm,
#vlocity textarea.form-group-sm .form-control,
#vlocity select[multiple].input-sm,
#vlocity select[multiple].form-group-sm .form-control {
  height: auto;
}
#vlocity .input-lg,
#vlocity .form-group-lg .form-control {
  height: 46px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.33;
  border-radius: 6px;
}
#vlocity select.input-lg,
#vlocity select.form-group-lg .form-control {
  height: 46px;
  line-height: 46px;
}
#vlocity textarea.input-lg,
#vlocity textarea.form-group-lg .form-control,
#vlocity select[multiple].input-lg,
#vlocity select[multiple].form-group-lg .form-control {
  height: auto;
}
#vlocity .has-feedback {
  position: relative;
}
#vlocity .has-feedback .form-control {
  padding-right: 42.5px;
}
#vlocity .form-control-feedback {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 2;
  display: block;
  width: 34px;
  height: 34px;
  line-height: 34px;
  text-align: center;
  pointer-events: none;
}
#vlocity .input-lg + .form-control-feedback {
  width: 46px;
  height: 46px;
  line-height: 46px;
}
#vlocity .input-sm + .form-control-feedback {
  width: 30px;
  height: 30px;
  line-height: 30px;
}
#vlocity .has-success .help-block,
#vlocity .has-success .control-label,
#vlocity .has-success .radio,
#vlocity .has-success .checkbox,
#vlocity .has-success .radio-inline,
#vlocity .has-success .checkbox-inline,
#vlocity .has-success.radio label,
#vlocity .has-success.checkbox label,
#vlocity .has-success.radio-inline label,
#vlocity .has-success.checkbox-inline label {
  color: #3c763d;
}
#vlocity .has-success .form-control {
  border-color: #3c763d;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
#vlocity .has-success .form-control:focus {
  border-color: #2b542c;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
}
#vlocity .has-success .input-group-addon {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #3c763d;
}
#vlocity .has-success .form-control-feedback {
  color: #3c763d;
}
#vlocity .has-warning .help-block,
#vlocity .has-warning .control-label,
#vlocity .has-warning .radio,
#vlocity .has-warning .checkbox,
#vlocity .has-warning .radio-inline,
#vlocity .has-warning .checkbox-inline,
#vlocity .has-warning.radio label,
#vlocity .has-warning.checkbox label,
#vlocity .has-warning.radio-inline label,
#vlocity .has-warning.checkbox-inline label {
  color: #8a6d3b;
}
#vlocity .has-warning .form-control {
  border-color: #8a6d3b;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
#vlocity .has-warning .form-control:focus {
  border-color: #66512c;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
}
#vlocity .has-warning .input-group-addon {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #8a6d3b;
}
#vlocity .has-warning .form-control-feedback {
  color: #8a6d3b;
}
#vlocity .has-error .help-block,
#vlocity .has-error .control-label,
#vlocity .has-error .radio,
#vlocity .has-error .checkbox,
#vlocity .has-error .radio-inline,
#vlocity .has-error .checkbox-inline,
#vlocity .has-error.radio label,
#vlocity .has-error.checkbox label,
#vlocity .has-error.radio-inline label,
#vlocity .has-error.checkbox-inline label {
  color: #a94442;
}
#vlocity .has-error .form-control {
  border-color: #a94442;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
#vlocity .has-error .form-control:focus {
  border-color: #843534;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
}
#vlocity .has-error .input-group-addon {
  color: #a94442;
  background-color: #f2dede;
  border-color: #a94442;
}
#vlocity .has-error .form-control-feedback {
  color: #a94442;
}
#vlocity .has-feedback label ~ .form-control-feedback {
  top: 25px;
}
#vlocity .has-feedback label.sr-only ~ .form-control-feedback {
  top: 0;
}
#vlocity .help-block {
  display: block;
  margin-top: 5px;
  margin-bottom: 10px;
  color: #737373;
}
@media (min-width: 768px) {
  #vlocity .form-inline .form-group {
    display: inline-block;
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .form-inline .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
  }
  #vlocity .form-inline .form-control-static {
    display: inline-block;
  }
  #vlocity .form-inline .input-group {
    display: inline-table;
    vertical-align: middle;
  }
  #vlocity .form-inline .input-group .input-group-addon,
  #vlocity .form-inline .input-group .input-group-btn,
  #vlocity .form-inline .input-group .form-control {
    width: auto;
  }
  #vlocity .form-inline .input-group > .form-control {
    width: 100%;
  }
  #vlocity .form-inline .control-label {
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .form-inline .radio,
  #vlocity .form-inline .checkbox {
    display: inline-block;
    margin-top: 0;
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .form-inline .radio label,
  #vlocity .form-inline .checkbox label {
    padding-left: 0;
  }
  #vlocity .form-inline .radio input[type="radio"],
  #vlocity .form-inline .checkbox input[type="checkbox"] {
    position: relative;
    margin-left: 0;
  }
  #vlocity .form-inline .has-feedback .form-control-feedback {
    top: 0;
  }
}
#vlocity .form-horizontal .radio,
#vlocity .form-horizontal .checkbox,
#vlocity .form-horizontal .radio-inline,
#vlocity .form-horizontal .checkbox-inline {
  padding-top: 7px;
  margin-top: 0;
  margin-bottom: 0;
}
#vlocity .form-horizontal .radio,
#vlocity .form-horizontal .checkbox {
  min-height: 27px;
}
#vlocity .form-horizontal .form-group {
  margin-right: -15px;
  margin-left: -15px;
}
@media (min-width: 768px) {
  #vlocity .form-horizontal .control-label {
    padding-top: 7px;
    margin-bottom: 0;
    text-align: right;
  }
}
#vlocity .form-horizontal .has-feedback .form-control-feedback {
  right: 15px;
}
@media (min-width: 768px) {
  #vlocity .form-horizontal .form-group-lg .control-label {
    padding-top: 14.3px;
  }
}
@media (min-width: 768px) {
  #vlocity .form-horizontal .form-group-sm .control-label {
    padding-top: 6px;
  }
}
#vlocity .btn {
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
  touch-action: manipulation;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}
#vlocity .btn:focus,
#vlocity .btn:active:focus,
#vlocity .btn.active:focus,
#vlocity .btn.focus,
#vlocity .btn:active.focus,
#vlocity .btn.active.focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
#vlocity .btn:hover,
#vlocity .btn:focus,
#vlocity .btn.focus {
  color: #333;
  text-decoration: none;
}
#vlocity .btn:active,
#vlocity .btn.active {
  background-image: none;
  outline: 0;
  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
#vlocity .btn.disabled,
#vlocity .btn[disabled],
#vlocity fieldset[disabled] .btn {
  pointer-events: none;
  cursor: not-allowed;
  filter: alpha(opacity=65);
  -webkit-box-shadow: none;
  box-shadow: none;
  opacity: .65;
}
#vlocity .btn-default {
  color: #333;
  background-color: #fff;
  border-color: #ccc;
}
#vlocity .btn-default:hover,
#vlocity .btn-default:focus,
#vlocity .btn-default.focus,
#vlocity .btn-default:active,
#vlocity .btn-default.active,
#vlocity .open > .dropdown-toggle.btn-default {
  color: #333;
  background-color: #e6e6e6;
  border-color: #adadad;
}
#vlocity .btn-default:active,
#vlocity .btn-default.active,
#vlocity .open > .dropdown-toggle.btn-default {
  background-image: none;
}
#vlocity .btn-default.disabled,
#vlocity .btn-default[disabled],
#vlocity fieldset[disabled] .btn-default,
#vlocity .btn-default.disabled:hover,
#vlocity .btn-default[disabled]:hover,
#vlocity fieldset[disabled] .btn-default:hover,
#vlocity .btn-default.disabled:focus,
#vlocity .btn-default[disabled]:focus,
#vlocity fieldset[disabled] .btn-default:focus,
#vlocity .btn-default.disabled.focus,
#vlocity .btn-default[disabled].focus,
#vlocity fieldset[disabled] .btn-default.focus,
#vlocity .btn-default.disabled:active,
#vlocity .btn-default[disabled]:active,
#vlocity fieldset[disabled] .btn-default:active,
#vlocity .btn-default.disabled.active,
#vlocity .btn-default[disabled].active,
#vlocity fieldset[disabled] .btn-default.active {
  background-color: #fff;
  border-color: #ccc;
}
#vlocity .btn-default .badge {
  color: #fff;
  background-color: #333;
}
#vlocity .btn-primary {
  color: #fff;
  background-color: #337ab7;
  border-color: #2e6da4;
}
#vlocity .btn-primary:hover,
#vlocity .btn-primary:focus,
#vlocity .btn-primary.focus,
#vlocity .btn-primary:active,
#vlocity .btn-primary.active,
#vlocity .open > .dropdown-toggle.btn-primary {
  color: #fff;
  background-color: #286090;
  border-color: #204d74;
}
#vlocity .btn-primary:active,
#vlocity .btn-primary.active,
#vlocity .open > .dropdown-toggle.btn-primary {
  background-image: none;
}
#vlocity .btn-primary.disabled,
#vlocity .btn-primary[disabled],
#vlocity fieldset[disabled] .btn-primary,
#vlocity .btn-primary.disabled:hover,
#vlocity .btn-primary[disabled]:hover,
#vlocity fieldset[disabled] .btn-primary:hover,
#vlocity .btn-primary.disabled:focus,
#vlocity .btn-primary[disabled]:focus,
#vlocity fieldset[disabled] .btn-primary:focus,
#vlocity .btn-primary.disabled.focus,
#vlocity .btn-primary[disabled].focus,
#vlocity fieldset[disabled] .btn-primary.focus,
#vlocity .btn-primary.disabled:active,
#vlocity .btn-primary[disabled]:active,
#vlocity fieldset[disabled] .btn-primary:active,
#vlocity .btn-primary.disabled.active,
#vlocity .btn-primary[disabled].active,
#vlocity fieldset[disabled] .btn-primary.active {
  background-color: #337ab7;
  border-color: #2e6da4;
}
#vlocity .btn-primary .badge {
  color: #337ab7;
  background-color: #fff;
}
#vlocity .btn-success {
  color: #fff;
  background-color: #5cb85c;
  border-color: #4cae4c;
}
#vlocity .btn-success:hover,
#vlocity .btn-success:focus,
#vlocity .btn-success.focus,
#vlocity .btn-success:active,
#vlocity .btn-success.active,
#vlocity .open > .dropdown-toggle.btn-success {
  color: #fff;
  background-color: #449d44;
  border-color: #398439;
}
#vlocity .btn-success:active,
#vlocity .btn-success.active,
#vlocity .open > .dropdown-toggle.btn-success {
  background-image: none;
}
#vlocity .btn-success.disabled,
#vlocity .btn-success[disabled],
#vlocity fieldset[disabled] .btn-success,
#vlocity .btn-success.disabled:hover,
#vlocity .btn-success[disabled]:hover,
#vlocity fieldset[disabled] .btn-success:hover,
#vlocity .btn-success.disabled:focus,
#vlocity .btn-success[disabled]:focus,
#vlocity fieldset[disabled] .btn-success:focus,
#vlocity .btn-success.disabled.focus,
#vlocity .btn-success[disabled].focus,
#vlocity fieldset[disabled] .btn-success.focus,
#vlocity .btn-success.disabled:active,
#vlocity .btn-success[disabled]:active,
#vlocity fieldset[disabled] .btn-success:active,
#vlocity .btn-success.disabled.active,
#vlocity .btn-success[disabled].active,
#vlocity fieldset[disabled] .btn-success.active {
  background-color: #5cb85c;
  border-color: #4cae4c;
}
#vlocity .btn-success .badge {
  color: #5cb85c;
  background-color: #fff;
}
#vlocity .btn-info {
  color: #fff;
  background-color: #5bc0de;
  border-color: #46b8da;
}
#vlocity .btn-info:hover,
#vlocity .btn-info:focus,
#vlocity .btn-info.focus,
#vlocity .btn-info:active,
#vlocity .btn-info.active,
#vlocity .open > .dropdown-toggle.btn-info {
  color: #fff;
  background-color: #31b0d5;
  border-color: #269abc;
}
#vlocity .btn-info:active,
#vlocity .btn-info.active,
#vlocity .open > .dropdown-toggle.btn-info {
  background-image: none;
}
#vlocity .btn-info.disabled,
#vlocity .btn-info[disabled],
#vlocity fieldset[disabled] .btn-info,
#vlocity .btn-info.disabled:hover,
#vlocity .btn-info[disabled]:hover,
#vlocity fieldset[disabled] .btn-info:hover,
#vlocity .btn-info.disabled:focus,
#vlocity .btn-info[disabled]:focus,
#vlocity fieldset[disabled] .btn-info:focus,
#vlocity .btn-info.disabled.focus,
#vlocity .btn-info[disabled].focus,
#vlocity fieldset[disabled] .btn-info.focus,
#vlocity .btn-info.disabled:active,
#vlocity .btn-info[disabled]:active,
#vlocity fieldset[disabled] .btn-info:active,
#vlocity .btn-info.disabled.active,
#vlocity .btn-info[disabled].active,
#vlocity fieldset[disabled] .btn-info.active {
  background-color: #5bc0de;
  border-color: #46b8da;
}
#vlocity .btn-info .badge {
  color: #5bc0de;
  background-color: #fff;
}
#vlocity .btn-warning {
  color: #fff;
  background-color: #f0ad4e;
  border-color: #eea236;
}
#vlocity .btn-warning:hover,
#vlocity .btn-warning:focus,
#vlocity .btn-warning.focus,
#vlocity .btn-warning:active,
#vlocity .btn-warning.active,
#vlocity .open > .dropdown-toggle.btn-warning {
  color: #fff;
  background-color: #ec971f;
  border-color: #d58512;
}
#vlocity .btn-warning:active,
#vlocity .btn-warning.active,
#vlocity .open > .dropdown-toggle.btn-warning {
  background-image: none;
}
#vlocity .btn-warning.disabled,
#vlocity .btn-warning[disabled],
#vlocity fieldset[disabled] .btn-warning,
#vlocity .btn-warning.disabled:hover,
#vlocity .btn-warning[disabled]:hover,
#vlocity fieldset[disabled] .btn-warning:hover,
#vlocity .btn-warning.disabled:focus,
#vlocity .btn-warning[disabled]:focus,
#vlocity fieldset[disabled] .btn-warning:focus,
#vlocity .btn-warning.disabled.focus,
#vlocity .btn-warning[disabled].focus,
#vlocity fieldset[disabled] .btn-warning.focus,
#vlocity .btn-warning.disabled:active,
#vlocity .btn-warning[disabled]:active,
#vlocity fieldset[disabled] .btn-warning:active,
#vlocity .btn-warning.disabled.active,
#vlocity .btn-warning[disabled].active,
#vlocity fieldset[disabled] .btn-warning.active {
  background-color: #f0ad4e;
  border-color: #eea236;
}
#vlocity .btn-warning .badge {
  color: #f0ad4e;
  background-color: #fff;
}
#vlocity .btn-danger {
  color: #fff;
  background-color: #d9534f;
  border-color: #d43f3a;
}
#vlocity .btn-danger:hover,
#vlocity .btn-danger:focus,
#vlocity .btn-danger.focus,
#vlocity .btn-danger:active,
#vlocity .btn-danger.active,
#vlocity .open > .dropdown-toggle.btn-danger {
  color: #fff;
  background-color: #c9302c;
  border-color: #ac2925;
}
#vlocity .btn-danger:active,
#vlocity .btn-danger.active,
#vlocity .open > .dropdown-toggle.btn-danger {
  background-image: none;
}
#vlocity .btn-danger.disabled,
#vlocity .btn-danger[disabled],
#vlocity fieldset[disabled] .btn-danger,
#vlocity .btn-danger.disabled:hover,
#vlocity .btn-danger[disabled]:hover,
#vlocity fieldset[disabled] .btn-danger:hover,
#vlocity .btn-danger.disabled:focus,
#vlocity .btn-danger[disabled]:focus,
#vlocity fieldset[disabled] .btn-danger:focus,
#vlocity .btn-danger.disabled.focus,
#vlocity .btn-danger[disabled].focus,
#vlocity fieldset[disabled] .btn-danger.focus,
#vlocity .btn-danger.disabled:active,
#vlocity .btn-danger[disabled]:active,
#vlocity fieldset[disabled] .btn-danger:active,
#vlocity .btn-danger.disabled.active,
#vlocity .btn-danger[disabled].active,
#vlocity fieldset[disabled] .btn-danger.active {
  background-color: #d9534f;
  border-color: #d43f3a;
}
#vlocity .btn-danger .badge {
  color: #d9534f;
  background-color: #fff;
}
#vlocity .btn-link {
  font-weight: normal;
  color: #337ab7;
  border-radius: 0;
}
#vlocity .btn-link,
#vlocity .btn-link:active,
#vlocity .btn-link.active,
#vlocity .btn-link[disabled],
#vlocity fieldset[disabled] .btn-link {
  background-color: transparent;
  -webkit-box-shadow: none;
  box-shadow: none;
}
#vlocity .btn-link,
#vlocity .btn-link:hover,
#vlocity .btn-link:focus,
#vlocity .btn-link:active {
  border-color: transparent;
}
#vlocity .btn-link:hover,
#vlocity .btn-link:focus {
  color: #23527c;
  text-decoration: underline;
  background-color: transparent;
}
#vlocity .btn-link[disabled]:hover,
#vlocity fieldset[disabled] .btn-link:hover,
#vlocity .btn-link[disabled]:focus,
#vlocity fieldset[disabled] .btn-link:focus {
  color: #777;
  text-decoration: none;
}
#vlocity .btn-lg,
#vlocity .btn-group-lg > .btn {
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.33;
  border-radius: 6px;
}
#vlocity .btn-sm,
#vlocity .btn-group-sm > .btn {
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
#vlocity .btn-xs,
#vlocity .btn-group-xs > .btn {
  padding: 1px 5px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
#vlocity .btn-block {
  display: block;
  width: 100%;
}
#vlocity .btn-block + .btn-block {
  margin-top: 5px;
}
#vlocity input[type="submit"].btn-block,
#vlocity input[type="reset"].btn-block,
#vlocity input[type="button"].btn-block {
  width: 100%;
}
#vlocity .fade {
  opacity: 0;
  -webkit-transition: opacity .15s linear;
  -o-transition: opacity .15s linear;
  transition: opacity .15s linear;
}
#vlocity .fade.in {
  opacity: 1;
}
#vlocity .collapse {
  display: none;
  visibility: hidden;
}
#vlocity .collapse.in {
  display: block;
  visibility: visible;
}
#vlocity tr.collapse.in {
  display: table-row;
}
#vlocity tbody.collapse.in {
  display: table-row-group;
}
#vlocity .collapsing {
  position: relative;
  height: 0;
  overflow: hidden;
  -webkit-transition-timing-function: ease;
  -o-transition-timing-function: ease;
  transition-timing-function: ease;
  -webkit-transition-duration: .35s;
  -o-transition-duration: .35s;
  transition-duration: .35s;
  -webkit-transition-property: height, visibility;
  -o-transition-property: height, visibility;
  transition-property: height, visibility;
}
#vlocity .caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top: 4px solid;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
}
#vlocity .dropdown {
  position: relative;
}
#vlocity .dropdown-toggle:focus {
  outline: 0;
}
#vlocity .dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  font-size: 14px;
  text-align: left;
  list-style: none;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
}
#vlocity .dropdown-menu.pull-right {
  right: 0;
  left: auto;
}
#vlocity .dropdown-menu .divider {
  height: 1px;
  margin: 9px 0;
  overflow: hidden;
  background-color: #e5e5e5;
}
#vlocity .dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333;
  white-space: nowrap;
}
#vlocity .dropdown-menu > li > a:hover,
#vlocity .dropdown-menu > li > a:focus {
  color: #262626;
  text-decoration: none;
  background-color: #f5f5f5;
}
#vlocity .dropdown-menu > .active > a,
#vlocity .dropdown-menu > .active > a:hover,
#vlocity .dropdown-menu > .active > a:focus {
  color: #fff;
  text-decoration: none;
  background-color: #337ab7;
  outline: 0;
}
#vlocity .dropdown-menu > .disabled > a,
#vlocity .dropdown-menu > .disabled > a:hover,
#vlocity .dropdown-menu > .disabled > a:focus {
  color: #777;
}
#vlocity .dropdown-menu > .disabled > a:hover,
#vlocity .dropdown-menu > .disabled > a:focus {
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
  background-image: none;
  filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
}
#vlocity .open > .dropdown-menu {
  display: block;
}
#vlocity .open > a {
  outline: 0;
}
#vlocity .dropdown-menu-right {
  right: 0;
  left: auto;
}
#vlocity .dropdown-menu-left {
  right: auto;
  left: 0;
}
#vlocity .dropdown-header {
  display: block;
  padding: 3px 20px;
  font-size: 12px;
  line-height: 1.42857143;
  color: #777;
  white-space: nowrap;
}
#vlocity .dropdown-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 990;
}
#vlocity .pull-right > .dropdown-menu {
  right: 0;
  left: auto;
}
#vlocity .dropup .caret,
#vlocity .navbar-fixed-bottom .dropdown .caret {
  content: "";
  border-top: 0;
  border-bottom: 4px solid;
}
#vlocity .dropup .dropdown-menu,
#vlocity .navbar-fixed-bottom .dropdown .dropdown-menu {
  top: auto;
  bottom: 100%;
  margin-bottom: 1px;
}
@media (min-width: 768px) {
  #vlocity .navbar-right .dropdown-menu {
    right: 0;
    left: auto;
  }
  #vlocity .navbar-right .dropdown-menu-left {
    right: auto;
    left: 0;
  }
}
#vlocity .btn-group,
#vlocity .btn-group-vertical {
  position: relative;
  display: inline-block;
  vertical-align: middle;
}
#vlocity .btn-group > .btn,
#vlocity .btn-group-vertical > .btn {
  position: relative;
  float: left;
}
#vlocity .btn-group > .btn:hover,
#vlocity .btn-group-vertical > .btn:hover,
#vlocity .btn-group > .btn:focus,
#vlocity .btn-group-vertical > .btn:focus,
#vlocity .btn-group > .btn:active,
#vlocity .btn-group-vertical > .btn:active,
#vlocity .btn-group > .btn.active,
#vlocity .btn-group-vertical > .btn.active {
  z-index: 2;
}
#vlocity .btn-group .btn + .btn,
#vlocity .btn-group .btn + .btn-group,
#vlocity .btn-group .btn-group + .btn,
#vlocity .btn-group .btn-group + .btn-group {
  margin-left: -1px;
}
#vlocity .btn-toolbar {
  margin-left: -5px;
}
#vlocity .btn-toolbar .btn-group,
#vlocity .btn-toolbar .input-group {
  float: left;
}
#vlocity .btn-toolbar > .btn,
#vlocity .btn-toolbar > .btn-group,
#vlocity .btn-toolbar > .input-group {
  margin-left: 5px;
}
#vlocity .btn-group > .btn:not(:first-child):not(:last-child):not(.dropdown-toggle) {
  border-radius: 0;
}
#vlocity .btn-group > .btn:first-child {
  margin-left: 0;
}
#vlocity .btn-group > .btn:first-child:not(:last-child):not(.dropdown-toggle) {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
#vlocity .btn-group > .btn:last-child:not(:first-child),
#vlocity .btn-group > .dropdown-toggle:not(:first-child) {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .btn-group > .btn-group {
  float: left;
}
#vlocity .btn-group > .btn-group:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
#vlocity .btn-group > .btn-group:first-child > .btn:last-child,
#vlocity .btn-group > .btn-group:first-child > .dropdown-toggle {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
#vlocity .btn-group > .btn-group:last-child > .btn:first-child {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .btn-group .dropdown-toggle:active,
#vlocity .btn-group.open .dropdown-toggle {
  outline: 0;
}
#vlocity .btn-group > .btn + .dropdown-toggle {
  padding-right: 8px;
  padding-left: 8px;
}
#vlocity .btn-group > .btn-lg + .dropdown-toggle {
  padding-right: 12px;
  padding-left: 12px;
}
#vlocity .btn-group.open .dropdown-toggle {
  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
#vlocity .btn-group.open .dropdown-toggle.btn-link {
  -webkit-box-shadow: none;
  box-shadow: none;
}
#vlocity .btn .caret {
  margin-left: 0;
}
#vlocity .btn-lg .caret {
  border-width: 5px 5px 0;
  border-bottom-width: 0;
}
#vlocity .dropup .btn-lg .caret {
  border-width: 0 5px 5px;
}
#vlocity .btn-group-vertical > .btn,
#vlocity .btn-group-vertical > .btn-group,
#vlocity .btn-group-vertical > .btn-group > .btn {
  display: block;
  float: none;
  width: 100%;
  max-width: 100%;
}
#vlocity .btn-group-vertical > .btn-group > .btn {
  float: none;
}
#vlocity .btn-group-vertical > .btn + .btn,
#vlocity .btn-group-vertical > .btn + .btn-group,
#vlocity .btn-group-vertical > .btn-group + .btn,
#vlocity .btn-group-vertical > .btn-group + .btn-group {
  margin-top: -1px;
  margin-left: 0;
}
#vlocity .btn-group-vertical > .btn:not(:first-child):not(:last-child) {
  border-radius: 0;
}
#vlocity .btn-group-vertical > .btn:first-child:not(:last-child) {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .btn-group-vertical > .btn:last-child:not(:first-child) {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  border-bottom-left-radius: 4px;
}
#vlocity .btn-group-vertical > .btn-group:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
#vlocity .btn-group-vertical > .btn-group:first-child:not(:last-child) > .btn:last-child,
#vlocity .btn-group-vertical > .btn-group:first-child:not(:last-child) > .dropdown-toggle {
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .btn-group-vertical > .btn-group:last-child:not(:first-child) > .btn:first-child {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#vlocity .btn-group-justified {
  display: table;
  width: 100%;
  table-layout: fixed;
  border-collapse: separate;
}
#vlocity .btn-group-justified > .btn,
#vlocity .btn-group-justified > .btn-group {
  display: table-cell;
  float: none;
  width: 1%;
}
#vlocity .btn-group-justified > .btn-group .btn {
  width: 100%;
}
#vlocity .btn-group-justified > .btn-group .dropdown-menu {
  left: auto;
}
#vlocity [data-toggle="buttons"] > .btn input[type="radio"],
#vlocity [data-toggle="buttons"] > .btn-group > .btn input[type="radio"],
#vlocity [data-toggle="buttons"] > .btn input[type="checkbox"],
#vlocity [data-toggle="buttons"] > .btn-group > .btn input[type="checkbox"] {
  position: absolute;
  clip: rect(0, 0, 0, 0);
  pointer-events: none;
}
#vlocity .input-group {
  position: relative;
  display: table;
  border-collapse: separate;
}
#vlocity .input-group[class*="col-"] {
  float: none;
  padding-right: 0;
  padding-left: 0;
}
#vlocity .input-group .form-control {
  position: relative;
  z-index: 2;
  float: left;
  width: 100%;
  margin-bottom: 0;
}
#vlocity .input-group-lg > .form-control,
#vlocity .input-group-lg > .input-group-addon,
#vlocity .input-group-lg > .input-group-btn > .btn {
  height: 46px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.33;
  border-radius: 6px;
}
#vlocity select.input-group-lg > .form-control,
#vlocity select.input-group-lg > .input-group-addon,
#vlocity select.input-group-lg > .input-group-btn > .btn {
  height: 46px;
  line-height: 46px;
}
#vlocity textarea.input-group-lg > .form-control,
#vlocity textarea.input-group-lg > .input-group-addon,
#vlocity textarea.input-group-lg > .input-group-btn > .btn,
#vlocity select[multiple].input-group-lg > .form-control,
#vlocity select[multiple].input-group-lg > .input-group-addon,
#vlocity select[multiple].input-group-lg > .input-group-btn > .btn {
  height: auto;
}
#vlocity .input-group-sm > .form-control,
#vlocity .input-group-sm > .input-group-addon,
#vlocity .input-group-sm > .input-group-btn > .btn {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
#vlocity select.input-group-sm > .form-control,
#vlocity select.input-group-sm > .input-group-addon,
#vlocity select.input-group-sm > .input-group-btn > .btn {
  height: 30px;
  line-height: 30px;
}
#vlocity textarea.input-group-sm > .form-control,
#vlocity textarea.input-group-sm > .input-group-addon,
#vlocity textarea.input-group-sm > .input-group-btn > .btn,
#vlocity select[multiple].input-group-sm > .form-control,
#vlocity select[multiple].input-group-sm > .input-group-addon,
#vlocity select[multiple].input-group-sm > .input-group-btn > .btn {
  height: auto;
}
#vlocity .input-group-addon,
#vlocity .input-group-btn,
#vlocity .input-group .form-control {
  display: table-cell;
}
#vlocity .input-group-addon:not(:first-child):not(:last-child),
#vlocity .input-group-btn:not(:first-child):not(:last-child),
#vlocity .input-group .form-control:not(:first-child):not(:last-child) {
  border-radius: 0;
}
#vlocity .input-group-addon,
#vlocity .input-group-btn {
  width: 1%;
  white-space: nowrap;
  vertical-align: middle;
}
#vlocity .input-group-addon {
  padding: 6px 12px;
  font-size: 14px;
  font-weight: normal;
  line-height: 1;
  color: #555;
  text-align: center;
  background-color: #eee;
  border: 1px solid #ccc;
  border-radius: 4px;
}
#vlocity .input-group-addon.input-sm {
  padding: 5px 10px;
  font-size: 12px;
  border-radius: 3px;
}
#vlocity .input-group-addon.input-lg {
  padding: 10px 16px;
  font-size: 18px;
  border-radius: 6px;
}
#vlocity .input-group-addon input[type="radio"],
#vlocity .input-group-addon input[type="checkbox"] {
  margin-top: 0;
}
#vlocity .input-group .form-control:first-child,
#vlocity .input-group-addon:first-child,
#vlocity .input-group-btn:first-child > .btn,
#vlocity .input-group-btn:first-child > .btn-group > .btn,
#vlocity .input-group-btn:first-child > .dropdown-toggle,
#vlocity .input-group-btn:last-child > .btn:not(:last-child):not(.dropdown-toggle),
#vlocity .input-group-btn:last-child > .btn-group:not(:last-child) > .btn {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
#vlocity .input-group-addon:first-child {
  border-right: 0;
}
#vlocity .input-group .form-control:last-child,
#vlocity .input-group-addon:last-child,
#vlocity .input-group-btn:last-child > .btn,
#vlocity .input-group-btn:last-child > .btn-group > .btn,
#vlocity .input-group-btn:last-child > .dropdown-toggle,
#vlocity .input-group-btn:first-child > .btn:not(:first-child),
#vlocity .input-group-btn:first-child > .btn-group:not(:first-child) > .btn {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .input-group-addon:last-child {
  border-left: 0;
}
#vlocity .input-group-btn {
  position: relative;
  font-size: 0;
  white-space: nowrap;
}
#vlocity .input-group-btn > .btn {
  position: relative;
}
#vlocity .input-group-btn > .btn + .btn {
  margin-left: -1px;
}
#vlocity .input-group-btn > .btn:hover,
#vlocity .input-group-btn > .btn:focus,
#vlocity .input-group-btn > .btn:active {
  z-index: 2;
}
#vlocity .input-group-btn:first-child > .btn,
#vlocity .input-group-btn:first-child > .btn-group {
  margin-right: -1px;
}
#vlocity .input-group-btn:last-child > .btn,
#vlocity .input-group-btn:last-child > .btn-group {
  margin-left: -1px;
}
#vlocity .nav {
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
#vlocity .nav > li {
  position: relative;
  display: block;
}
#vlocity .nav > li > a {
  position: relative;
  display: block;
  padding: 10px 15px;
}
#vlocity .nav > li > a:hover,
#vlocity .nav > li > a:focus {
  text-decoration: none;
  background-color: #eee;
}
#vlocity .nav > li.disabled > a {
  color: #777;
}
#vlocity .nav > li.disabled > a:hover,
#vlocity .nav > li.disabled > a:focus {
  color: #777;
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
}
#vlocity .nav .open > a,
#vlocity .nav .open > a:hover,
#vlocity .nav .open > a:focus {
  background-color: #eee;
  border-color: #337ab7;
}
#vlocity .nav .nav-divider {
  height: 1px;
  margin: 9px 0;
  overflow: hidden;
  background-color: #e5e5e5;
}
#vlocity .nav > li > a > img {
  max-width: none;
}
#vlocity .nav-tabs {
  border-bottom: 1px solid #ddd;
}
#vlocity .nav-tabs > li {
  float: left;
  margin-bottom: -1px;
}
#vlocity .nav-tabs > li > a {
  margin-right: 2px;
  line-height: 1.42857143;
  border: 1px solid transparent;
  border-radius: 4px 4px 0 0;
}
#vlocity .nav-tabs > li > a:hover {
  border-color: #eee #eee #ddd;
}
#vlocity .nav-tabs > li.active > a,
#vlocity .nav-tabs > li.active > a:hover,
#vlocity .nav-tabs > li.active > a:focus {
  color: #555;
  cursor: default;
  background-color: #fff;
  border: 1px solid #ddd;
  border-bottom-color: transparent;
}
#vlocity .nav-tabs.nav-justified {
  width: 100%;
  border-bottom: 0;
}
#vlocity .nav-tabs.nav-justified > li {
  float: none;
}
#vlocity .nav-tabs.nav-justified > li > a {
  margin-bottom: 5px;
  text-align: center;
}
#vlocity .nav-tabs.nav-justified > .dropdown .dropdown-menu {
  top: auto;
  left: auto;
}
@media (min-width: 768px) {
  #vlocity .nav-tabs.nav-justified > li {
    display: table-cell;
    width: 1%;
  }
  #vlocity .nav-tabs.nav-justified > li > a {
    margin-bottom: 0;
  }
}
#vlocity .nav-tabs.nav-justified > li > a {
  margin-right: 0;
  border-radius: 4px;
}
#vlocity .nav-tabs.nav-justified > .active > a,
#vlocity .nav-tabs.nav-justified > .active > a:hover,
#vlocity .nav-tabs.nav-justified > .active > a:focus {
  border: 1px solid #ddd;
}
@media (min-width: 768px) {
  #vlocity .nav-tabs.nav-justified > li > a {
    border-bottom: 1px solid #ddd;
    border-radius: 4px 4px 0 0;
  }
  #vlocity .nav-tabs.nav-justified > .active > a,
  #vlocity .nav-tabs.nav-justified > .active > a:hover,
  #vlocity .nav-tabs.nav-justified > .active > a:focus {
    border-bottom-color: #fff;
  }
}
#vlocity .nav-pills > li {
  float: left;
}
#vlocity .nav-pills > li > a {
  border-radius: 4px;
}
#vlocity .nav-pills > li + li {
  margin-left: 2px;
}
#vlocity .nav-pills > li.active > a,
#vlocity .nav-pills > li.active > a:hover,
#vlocity .nav-pills > li.active > a:focus {
  color: #fff;
  background-color: #337ab7;
}
#vlocity .nav-stacked > li {
  float: none;
}
#vlocity .nav-stacked > li + li {
  margin-top: 2px;
  margin-left: 0;
}
#vlocity .nav-justified {
  width: 100%;
}
#vlocity .nav-justified > li {
  float: none;
}
#vlocity .nav-justified > li > a {
  margin-bottom: 5px;
  text-align: center;
}
#vlocity .nav-justified > .dropdown .dropdown-menu {
  top: auto;
  left: auto;
}
@media (min-width: 768px) {
  #vlocity .nav-justified > li {
    display: table-cell;
    width: 1%;
  }
  #vlocity .nav-justified > li > a {
    margin-bottom: 0;
  }
}
#vlocity .nav-tabs-justified {
  border-bottom: 0;
}
#vlocity .nav-tabs-justified > li > a {
  margin-right: 0;
  border-radius: 4px;
}
#vlocity .nav-tabs-justified > .active > a,
#vlocity .nav-tabs-justified > .active > a:hover,
#vlocity .nav-tabs-justified > .active > a:focus {
  border: 1px solid #ddd;
}
@media (min-width: 768px) {
  #vlocity .nav-tabs-justified > li > a {
    border-bottom: 1px solid #ddd;
    border-radius: 4px 4px 0 0;
  }
  #vlocity .nav-tabs-justified > .active > a,
  #vlocity .nav-tabs-justified > .active > a:hover,
  #vlocity .nav-tabs-justified > .active > a:focus {
    border-bottom-color: #fff;
  }
}
#vlocity .tab-content > .tab-pane {
  display: none;
  visibility: hidden;
}
#vlocity .tab-content > .active {
  display: block;
  visibility: visible;
}
#vlocity .nav-tabs .dropdown-menu {
  margin-top: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#vlocity .navbar {
  position: relative;
  min-height: 50px;
  margin-bottom: 20px;
  border: 1px solid transparent;
}
@media (min-width: 768px) {
  #vlocity .navbar {
    border-radius: 4px;
  }
}
@media (min-width: 768px) {
  #vlocity .navbar-header {
    float: left;
  }
}
#vlocity .navbar-collapse {
  padding-right: 15px;
  padding-left: 15px;
  overflow-x: visible;
  -webkit-overflow-scrolling: touch;
  border-top: 1px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);
}
#vlocity .navbar-collapse.in {
  overflow-y: auto;
}
@media (min-width: 768px) {
  #vlocity .navbar-collapse {
    width: auto;
    border-top: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
  #vlocity .navbar-collapse.collapse {
    display: block !important;
    height: auto !important;
    padding-bottom: 0;
    overflow: visible !important;
    visibility: visible !important;
  }
  #vlocity .navbar-collapse.in {
    overflow-y: visible;
  }
  #vlocity .navbar-fixed-top .navbar-collapse,
  #vlocity .navbar-static-top .navbar-collapse,
  #vlocity .navbar-fixed-bottom .navbar-collapse {
    padding-right: 0;
    padding-left: 0;
  }
}
#vlocity .navbar-fixed-top .navbar-collapse,
#vlocity .navbar-fixed-bottom .navbar-collapse {
  max-height: 340px;
}
@media (max-device-width: 480px) and (orientation: landscape) {
  #vlocity .navbar-fixed-top .navbar-collapse,
  #vlocity .navbar-fixed-bottom .navbar-collapse {
    max-height: 200px;
  }
}
#vlocity .container > .navbar-header,
#vlocity .container-fluid > .navbar-header,
#vlocity .container > .navbar-collapse,
#vlocity .container-fluid > .navbar-collapse {
  margin-right: -15px;
  margin-left: -15px;
}
@media (min-width: 768px) {
  #vlocity .container > .navbar-header,
  #vlocity .container-fluid > .navbar-header,
  #vlocity .container > .navbar-collapse,
  #vlocity .container-fluid > .navbar-collapse {
    margin-right: 0;
    margin-left: 0;
  }
}
#vlocity .navbar-static-top {
  z-index: 1000;
  border-width: 0 0 1px;
}
@media (min-width: 768px) {
  #vlocity .navbar-static-top {
    border-radius: 0;
  }
}
#vlocity .navbar-fixed-top,
#vlocity .navbar-fixed-bottom {
  position: fixed;
  right: 0;
  left: 0;
  z-index: 1030;
}
@media (min-width: 768px) {
  #vlocity .navbar-fixed-top,
  #vlocity .navbar-fixed-bottom {
    border-radius: 0;
  }
}
#vlocity .navbar-fixed-top {
  top: 0;
  border-width: 0 0 1px;
}
#vlocity .navbar-fixed-bottom {
  bottom: 0;
  margin-bottom: 0;
  border-width: 1px 0 0;
}
#vlocity .navbar-brand {
  float: left;
  height: 50px;
  padding: 15px 15px;
  font-size: 18px;
  line-height: 20px;
}
#vlocity .navbar-brand:hover,
#vlocity .navbar-brand:focus {
  text-decoration: none;
}
#vlocity .navbar-brand > img {
  display: block;
}
@media (min-width: 768px) {
  #vlocity .navbar > .container .navbar-brand,
  #vlocity .navbar > .container-fluid .navbar-brand {
    margin-left: -15px;
  }
}
#vlocity .navbar-toggle {
  position: relative;
  float: right;
  padding: 9px 10px;
  margin-top: 8px;
  margin-right: 15px;
  margin-bottom: 8px;
  background-color: transparent;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}
#vlocity .navbar-toggle:focus {
  outline: 0;
}
#vlocity .navbar-toggle .icon-bar {
  display: block;
  width: 22px;
  height: 2px;
  border-radius: 1px;
}
#vlocity .navbar-toggle .icon-bar + .icon-bar {
  margin-top: 4px;
}
@media (min-width: 768px) {
  #vlocity .navbar-toggle {
    display: none;
  }
}
#vlocity .navbar-nav {
  margin: 7.5px -15px;
}
#vlocity .navbar-nav > li > a {
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 20px;
}
@media (max-width: 767px) {
  #vlocity .navbar-nav .open .dropdown-menu {
    position: static;
    float: none;
    width: auto;
    margin-top: 0;
    background-color: transparent;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
  #vlocity .navbar-nav .open .dropdown-menu > li > a,
  #vlocity .navbar-nav .open .dropdown-menu .dropdown-header {
    padding: 5px 15px 5px 25px;
  }
  #vlocity .navbar-nav .open .dropdown-menu > li > a {
    line-height: 20px;
  }
  #vlocity .navbar-nav .open .dropdown-menu > li > a:hover,
  #vlocity .navbar-nav .open .dropdown-menu > li > a:focus {
    background-image: none;
  }
}
@media (min-width: 768px) {
  #vlocity .navbar-nav {
    float: left;
    margin: 0;
  }
  #vlocity .navbar-nav > li {
    float: left;
  }
  #vlocity .navbar-nav > li > a {
    padding-top: 15px;
    padding-bottom: 15px;
  }
}
#vlocity .navbar-form {
  padding: 10px 15px;
  margin-top: 8px;
  margin-right: -15px;
  margin-bottom: 8px;
  margin-left: -15px;
  border-top: 1px solid transparent;
  border-bottom: 1px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.1);
}
@media (min-width: 768px) {
  #vlocity .navbar-form .form-group {
    display: inline-block;
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .navbar-form .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
  }
  #vlocity .navbar-form .form-control-static {
    display: inline-block;
  }
  #vlocity .navbar-form .input-group {
    display: inline-table;
    vertical-align: middle;
  }
  #vlocity .navbar-form .input-group .input-group-addon,
  #vlocity .navbar-form .input-group .input-group-btn,
  #vlocity .navbar-form .input-group .form-control {
    width: auto;
  }
  #vlocity .navbar-form .input-group > .form-control {
    width: 100%;
  }
  #vlocity .navbar-form .control-label {
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .navbar-form .radio,
  #vlocity .navbar-form .checkbox {
    display: inline-block;
    margin-top: 0;
    margin-bottom: 0;
    vertical-align: middle;
  }
  #vlocity .navbar-form .radio label,
  #vlocity .navbar-form .checkbox label {
    padding-left: 0;
  }
  #vlocity .navbar-form .radio input[type="radio"],
  #vlocity .navbar-form .checkbox input[type="checkbox"] {
    position: relative;
    margin-left: 0;
  }
  #vlocity .navbar-form .has-feedback .form-control-feedback {
    top: 0;
  }
}
@media (max-width: 767px) {
  #vlocity .navbar-form .form-group {
    margin-bottom: 5px;
  }
  #vlocity .navbar-form .form-group:last-child {
    margin-bottom: 0;
  }
}
@media (min-width: 768px) {
  #vlocity .navbar-form {
    width: auto;
    padding-top: 0;
    padding-bottom: 0;
    margin-right: 0;
    margin-left: 0;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
}
#vlocity .navbar-nav > li > .dropdown-menu {
  margin-top: 0;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
#vlocity .navbar-fixed-bottom .navbar-nav > li > .dropdown-menu {
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
#vlocity .navbar-btn {
  margin-top: 8px;
  margin-bottom: 8px;
}
#vlocity .navbar-btn.btn-sm {
  margin-top: 10px;
  margin-bottom: 10px;
}
#vlocity .navbar-btn.btn-xs {
  margin-top: 14px;
  margin-bottom: 14px;
}
#vlocity .navbar-text {
  margin-top: 15px;
  margin-bottom: 15px;
}
@media (min-width: 768px) {
  #vlocity .navbar-text {
    float: left;
    margin-right: 15px;
    margin-left: 15px;
  }
}
@media (min-width: 768px) {
  #vlocity .navbar-left {
    float: left !important;
  }
  #vlocity .navbar-right {
    float: right !important;
    margin-right: -15px;
  }
  #vlocity .navbar-right ~ .navbar-right {
    margin-right: 0;
  }
}
#vlocity .navbar-default {
  background-color: #f8f8f8;
  border-color: #e7e7e7;
}
#vlocity .navbar-default .navbar-brand {
  color: #777;
}
#vlocity .navbar-default .navbar-brand:hover,
#vlocity .navbar-default .navbar-brand:focus {
  color: #5e5e5e;
  background-color: transparent;
}
#vlocity .navbar-default .navbar-text {
  color: #777;
}
#vlocity .navbar-default .navbar-nav > li > a {
  color: #777;
}
#vlocity .navbar-default .navbar-nav > li > a:hover,
#vlocity .navbar-default .navbar-nav > li > a:focus {
  color: #333;
  background-color: transparent;
}
#vlocity .navbar-default .navbar-nav > .active > a,
#vlocity .navbar-default .navbar-nav > .active > a:hover,
#vlocity .navbar-default .navbar-nav > .active > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
#vlocity .navbar-default .navbar-nav > .disabled > a,
#vlocity .navbar-default .navbar-nav > .disabled > a:hover,
#vlocity .navbar-default .navbar-nav > .disabled > a:focus {
  color: #ccc;
  background-color: transparent;
}
#vlocity .navbar-default .navbar-toggle {
  border-color: #ddd;
}
#vlocity .navbar-default .navbar-toggle:hover,
#vlocity .navbar-default .navbar-toggle:focus {
  background-color: #ddd;
}
#vlocity .navbar-default .navbar-toggle .icon-bar {
  background-color: #888;
}
#vlocity .navbar-default .navbar-collapse,
#vlocity .navbar-default .navbar-form {
  border-color: #e7e7e7;
}
#vlocity .navbar-default .navbar-nav > .open > a,
#vlocity .navbar-default .navbar-nav > .open > a:hover,
#vlocity .navbar-default .navbar-nav > .open > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
@media (max-width: 767px) {
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #777;
  }
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #333;
    background-color: transparent;
  }
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .active > a,
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #555;
    background-color: #e7e7e7;
  }
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a,
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a:hover,
  #vlocity .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a:focus {
    color: #ccc;
    background-color: transparent;
  }
}
#vlocity .navbar-default .navbar-link {
  color: #777;
}
#vlocity .navbar-default .navbar-link:hover {
  color: #333;
}
#vlocity .navbar-default .btn-link {
  color: #777;
}
#vlocity .navbar-default .btn-link:hover,
#vlocity .navbar-default .btn-link:focus {
  color: #333;
}
#vlocity .navbar-default .btn-link[disabled]:hover,
#vlocity fieldset[disabled] .navbar-default .btn-link:hover,
#vlocity .navbar-default .btn-link[disabled]:focus,
#vlocity fieldset[disabled] .navbar-default .btn-link:focus {
  color: #ccc;
}
#vlocity .navbar-inverse {
  background-color: #222;
  border-color: #080808;
}
#vlocity .navbar-inverse .navbar-brand {
  color: #9d9d9d;
}
#vlocity .navbar-inverse .navbar-brand:hover,
#vlocity .navbar-inverse .navbar-brand:focus {
  color: #fff;
  background-color: transparent;
}
#vlocity .navbar-inverse .navbar-text {
  color: #9d9d9d;
}
#vlocity .navbar-inverse .navbar-nav > li > a {
  color: #9d9d9d;
}
#vlocity .navbar-inverse .navbar-nav > li > a:hover,
#vlocity .navbar-inverse .navbar-nav > li > a:focus {
  color: #fff;
  background-color: transparent;
}
#vlocity .navbar-inverse .navbar-nav > .active > a,
#vlocity .navbar-inverse .navbar-nav > .active > a:hover,
#vlocity .navbar-inverse .navbar-nav > .active > a:focus {
  color: #fff;
  background-color: #080808;
}
#vlocity .navbar-inverse .navbar-nav > .disabled > a,
#vlocity .navbar-inverse .navbar-nav > .disabled > a:hover,
#vlocity .navbar-inverse .navbar-nav > .disabled > a:focus {
  color: #444;
  background-color: transparent;
}
#vlocity .navbar-inverse .navbar-toggle {
  border-color: #333;
}
#vlocity .navbar-inverse .navbar-toggle:hover,
#vlocity .navbar-inverse .navbar-toggle:focus {
  background-color: #333;
}
#vlocity .navbar-inverse .navbar-toggle .icon-bar {
  background-color: #fff;
}
#vlocity .navbar-inverse .navbar-collapse,
#vlocity .navbar-inverse .navbar-form {
  border-color: #101010;
}
#vlocity .navbar-inverse .navbar-nav > .open > a,
#vlocity .navbar-inverse .navbar-nav > .open > a:hover,
#vlocity .navbar-inverse .navbar-nav > .open > a:focus {
  color: #fff;
  background-color: #080808;
}
@media (max-width: 767px) {
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .dropdown-header {
    border-color: #080808;
  }
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu .divider {
    background-color: #080808;
  }
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > li > a {
    color: #9d9d9d;
  }
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:hover,
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #fff;
    background-color: transparent;
  }
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a,
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:hover,
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #fff;
    background-color: #080808;
  }
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a,
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:hover,
  #vlocity .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:focus {
    color: #444;
    background-color: transparent;
  }
}
#vlocity .navbar-inverse .navbar-link {
  color: #9d9d9d;
}
#vlocity .navbar-inverse .navbar-link:hover {
  color: #fff;
}
#vlocity .navbar-inverse .btn-link {
  color: #9d9d9d;
}
#vlocity .navbar-inverse .btn-link:hover,
#vlocity .navbar-inverse .btn-link:focus {
  color: #fff;
}
#vlocity .navbar-inverse .btn-link[disabled]:hover,
#vlocity fieldset[disabled] .navbar-inverse .btn-link:hover,
#vlocity .navbar-inverse .btn-link[disabled]:focus,
#vlocity fieldset[disabled] .navbar-inverse .btn-link:focus {
  color: #444;
}
#vlocity .breadcrumb {
  padding: 8px 15px;
  margin-bottom: 20px;
  list-style: none;
  background-color: #f5f5f5;
  border-radius: 4px;
}
#vlocity .breadcrumb > li {
  display: inline-block;
}
#vlocity .breadcrumb > li + li:before {
  padding: 0 5px;
  color: #ccc;
  content: "/\00a0";
}
#vlocity .breadcrumb > .active {
  color: #777;
}
#vlocity .pagination {
  display: inline-block;
  padding-left: 0;
  margin: 20px 0;
  border-radius: 4px;
}
#vlocity .pagination > li {
  display: inline;
}
#vlocity .pagination > li > a,
#vlocity .pagination > li > span {
  position: relative;
  float: left;
  padding: 6px 12px;
  margin-left: -1px;
  line-height: 1.42857143;
  color: #337ab7;
  text-decoration: none;
  background-color: #fff;
  border: 1px solid #ddd;
}
#vlocity .pagination > li:first-child > a,
#vlocity .pagination > li:first-child > span {
  margin-left: 0;
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
}
#vlocity .pagination > li:last-child > a,
#vlocity .pagination > li:last-child > span {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}
#vlocity .pagination > li > a:hover,
#vlocity .pagination > li > span:hover,
#vlocity .pagination > li > a:focus,
#vlocity .pagination > li > span:focus {
  color: #23527c;
  background-color: #eee;
  border-color: #ddd;
}
#vlocity .pagination > .active > a,
#vlocity .pagination > .active > span,
#vlocity .pagination > .active > a:hover,
#vlocity .pagination > .active > span:hover,
#vlocity .pagination > .active > a:focus,
#vlocity .pagination > .active > span:focus {
  z-index: 2;
  color: #fff;
  cursor: default;
  background-color: #337ab7;
  border-color: #337ab7;
}
#vlocity .pagination > .disabled > span,
#vlocity .pagination > .disabled > span:hover,
#vlocity .pagination > .disabled > span:focus,
#vlocity .pagination > .disabled > a,
#vlocity .pagination > .disabled > a:hover,
#vlocity .pagination > .disabled > a:focus {
  color: #777;
  cursor: not-allowed;
  background-color: #fff;
  border-color: #ddd;
}
#vlocity .pagination-lg > li > a,
#vlocity .pagination-lg > li > span {
  padding: 10px 16px;
  font-size: 18px;
}
#vlocity .pagination-lg > li:first-child > a,
#vlocity .pagination-lg > li:first-child > span {
  border-top-left-radius: 6px;
  border-bottom-left-radius: 6px;
}
#vlocity .pagination-lg > li:last-child > a,
#vlocity .pagination-lg > li:last-child > span {
  border-top-right-radius: 6px;
  border-bottom-right-radius: 6px;
}
#vlocity .pagination-sm > li > a,
#vlocity .pagination-sm > li > span {
  padding: 5px 10px;
  font-size: 12px;
}
#vlocity .pagination-sm > li:first-child > a,
#vlocity .pagination-sm > li:first-child > span {
  border-top-left-radius: 3px;
  border-bottom-left-radius: 3px;
}
#vlocity .pagination-sm > li:last-child > a,
#vlocity .pagination-sm > li:last-child > span {
  border-top-right-radius: 3px;
  border-bottom-right-radius: 3px;
}
#vlocity .pager {
  padding-left: 0;
  margin: 20px 0;
  text-align: center;
  list-style: none;
}
#vlocity .pager li {
  display: inline;
}
#vlocity .pager li > a,
#vlocity .pager li > span {
  display: inline-block;
  padding: 5px 14px;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 15px;
}
#vlocity .pager li > a:hover,
#vlocity .pager li > a:focus {
  text-decoration: none;
  background-color: #eee;
}
#vlocity .pager .next > a,
#vlocity .pager .next > span {
  float: right;
}
#vlocity .pager .previous > a,
#vlocity .pager .previous > span {
  float: left;
}
#vlocity .pager .disabled > a,
#vlocity .pager .disabled > a:hover,
#vlocity .pager .disabled > a:focus,
#vlocity .pager .disabled > span {
  color: #777;
  cursor: not-allowed;
  background-color: #fff;
}
#vlocity .label {
  display: inline;
  padding: .2em .6em .3em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
}
#vlocity a.label:hover,
#vlocity a.label:focus {
  color: #fff;
  text-decoration: none;
  cursor: pointer;
}
#vlocity .label:empty {
  display: none;
}
#vlocity .btn .label {
  position: relative;
  top: -1px;
}
#vlocity .label-default {
  background-color: #777;
}
#vlocity .label-default[href]:hover,
#vlocity .label-default[href]:focus {
  background-color: #5e5e5e;
}
#vlocity .label-primary {
  background-color: #337ab7;
}
#vlocity .label-primary[href]:hover,
#vlocity .label-primary[href]:focus {
  background-color: #286090;
}
#vlocity .label-success {
  background-color: #5cb85c;
}
#vlocity .label-success[href]:hover,
#vlocity .label-success[href]:focus {
  background-color: #449d44;
}
#vlocity .label-info {
  background-color: #5bc0de;
}
#vlocity .label-info[href]:hover,
#vlocity .label-info[href]:focus {
  background-color: #31b0d5;
}
#vlocity .label-warning {
  background-color: #f0ad4e;
}
#vlocity .label-warning[href]:hover,
#vlocity .label-warning[href]:focus {
  background-color: #ec971f;
}
#vlocity .label-danger {
  background-color: #d9534f;
}
#vlocity .label-danger[href]:hover,
#vlocity .label-danger[href]:focus {
  background-color: #c9302c;
}
#vlocity .badge {
  display: inline-block;
  min-width: 10px;
  padding: 3px 7px;
  font-size: 12px;
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  background-color: #777;
  border-radius: 10px;
}
#vlocity .badge:empty {
  display: none;
}
#vlocity .btn .badge {
  position: relative;
  top: -1px;
}
#vlocity .btn-xs .badge {
  top: 0;
  padding: 1px 5px;
}
#vlocity a.badge:hover,
#vlocity a.badge:focus {
  color: #fff;
  text-decoration: none;
  cursor: pointer;
}
#vlocity .list-group-item.active > .badge,
#vlocity .nav-pills > .active > a > .badge {
  color: #337ab7;
  background-color: #fff;
}
#vlocity .list-group-item > .badge {
  float: right;
}
#vlocity .list-group-item > .badge + .badge {
  margin-right: 5px;
}
#vlocity .nav-pills > li > a > .badge {
  margin-left: 3px;
}
#vlocity .jumbotron {
  padding: 30px 15px;
  margin-bottom: 30px;
  color: inherit;
  background-color: #eee;
}
#vlocity .jumbotron h1,
#vlocity .jumbotron .h1 {
  color: inherit;
}
#vlocity .jumbotron p {
  margin-bottom: 15px;
  font-size: 21px;
  font-weight: 200;
}
#vlocity .jumbotron > hr {
  border-top-color: #d5d5d5;
}
#vlocity .container .jumbotron,
#vlocity .container-fluid .jumbotron {
  border-radius: 6px;
}
#vlocity .jumbotron .container {
  max-width: 100%;
}
@media screen and (min-width: 768px) {
  #vlocity .jumbotron {
    padding: 48px 0;
  }
  #vlocity .container .jumbotron,
  #vlocity .container-fluid .jumbotron {
    padding-right: 60px;
    padding-left: 60px;
  }
  #vlocity .jumbotron h1,
  #vlocity .jumbotron .h1 {
    font-size: 63px;
  }
}
#vlocity .thumbnail {
  display: block;
  padding: 4px;
  margin-bottom: 20px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: border 0.2s ease-in-out;
  -o-transition: border 0.2s ease-in-out;
  transition: border 0.2s ease-in-out;
}
#vlocity .thumbnail > img,
#vlocity .thumbnail a > img {
  margin-right: auto;
  margin-left: auto;
}
#vlocity a.thumbnail:hover,
#vlocity a.thumbnail:focus,
#vlocity a.thumbnail.active {
  border-color: #337ab7;
}
#vlocity .thumbnail .caption {
  padding: 9px;
  color: #333;
}
#vlocity .alert {
  padding: 15px;
  margin-bottom: 20px;
  border: 1px solid transparent;
  border-radius: 4px;
}
#vlocity .alert h4 {
  margin-top: 0;
  color: inherit;
}
#vlocity .alert .alert-link {
  font-weight: bold;
}
#vlocity .alert > p,
#vlocity .alert > ul {
  margin-bottom: 0;
}
#vlocity .alert > p + p {
  margin-top: 5px;
}
#vlocity .alert-dismissable,
#vlocity .alert-dismissible {
  padding-right: 35px;
}
#vlocity .alert-dismissable .close,
#vlocity .alert-dismissible .close {
  position: relative;
  top: -2px;
  right: -21px;
  color: inherit;
}
#vlocity .alert-success {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
#vlocity .alert-success hr {
  border-top-color: #c9e2b3;
}
#vlocity .alert-success .alert-link {
  color: #2b542c;
}
#vlocity .alert-info {
  color: #31708f;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
#vlocity .alert-info hr {
  border-top-color: #a6e1ec;
}
#vlocity .alert-info .alert-link {
  color: #245269;
}
#vlocity .alert-warning {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}
#vlocity .alert-warning hr {
  border-top-color: #f7e1b5;
}
#vlocity .alert-warning .alert-link {
  color: #66512c;
}
#vlocity .alert-danger {
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}
#vlocity .alert-danger hr {
  border-top-color: #e4b9c0;
}
#vlocity .alert-danger .alert-link {
  color: #843534;
}
@-webkit-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
@-o-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
@keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
#vlocity .progress {
  height: 20px;
  margin-bottom: 20px;
  overflow: hidden;
  background-color: #f5f5f5;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}
#vlocity .progress-bar {
  float: left;
  width: 0;
  height: 100%;
  font-size: 12px;
  line-height: 20px;
  color: #fff;
  text-align: center;
  background-color: #337ab7;
  -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
  -webkit-transition: width .6s ease;
  -o-transition: width .6s ease;
  transition: width .6s ease;
}
#vlocity .progress-striped .progress-bar,
#vlocity .progress-bar-striped {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  -webkit-background-size: 40px 40px;
  background-size: 40px 40px;
}
#vlocity .progress.active .progress-bar,
#vlocity .progress-bar.active {
  -webkit-animation: progress-bar-stripes 2s linear infinite;
  -o-animation: progress-bar-stripes 2s linear infinite;
  animation: progress-bar-stripes 2s linear infinite;
}
#vlocity .progress-bar-success {
  background-color: #5cb85c;
}
#vlocity .progress-striped .progress-bar-success {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
#vlocity .progress-bar-info {
  background-color: #5bc0de;
}
#vlocity .progress-striped .progress-bar-info {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
#vlocity .progress-bar-warning {
  background-color: #f0ad4e;
}
#vlocity .progress-striped .progress-bar-warning {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
#vlocity .progress-bar-danger {
  background-color: #d9534f;
}
#vlocity .progress-striped .progress-bar-danger {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
#vlocity .media {
  margin-top: 15px;
}
#vlocity .media:first-child {
  margin-top: 0;
}
#vlocity .media-right,
#vlocity .media > .pull-right {
  padding-left: 10px;
}
#vlocity .media-left,
#vlocity .media > .pull-left {
  padding-right: 10px;
}
#vlocity .media-left,
#vlocity .media-right,
#vlocity .media-body {
  display: table-cell;
  vertical-align: top;
}
#vlocity .media-middle {
  vertical-align: middle;
}
#vlocity .media-bottom {
  vertical-align: bottom;
}
#vlocity .media-heading {
  margin-top: 0;
  margin-bottom: 5px;
}
#vlocity .media-list {
  padding-left: 0;
  list-style: none;
}
#vlocity .list-group {
  padding-left: 0;
  margin-bottom: 20px;
}
#vlocity .list-group-item {
  position: relative;
  display: block;
  padding: 10px 15px;
  margin-bottom: -1px;
  background-color: #fff;
  border: 1px solid #ddd;
}
#vlocity .list-group-item:first-child {
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}
#vlocity .list-group-item:last-child {
  margin-bottom: 0;
  border-bottom-right-radius: 4px;
  border-bottom-left-radius: 4px;
}
#vlocity a.list-group-item {
  color: #555;
}
#vlocity a.list-group-item .list-group-item-heading {
  color: #333;
}
#vlocity a.list-group-item:hover,
#vlocity a.list-group-item:focus {
  color: #555;
  text-decoration: none;
  background-color: #f5f5f5;
}
#vlocity .list-group-item.disabled,
#vlocity .list-group-item.disabled:hover,
#vlocity .list-group-item.disabled:focus {
  color: #777;
  cursor: not-allowed;
  background-color: #eee;
}
#vlocity .list-group-item.disabled .list-group-item-heading,
#vlocity .list-group-item.disabled:hover .list-group-item-heading,
#vlocity .list-group-item.disabled:focus .list-group-item-heading {
  color: inherit;
}
#vlocity .list-group-item.disabled .list-group-item-text,
#vlocity .list-group-item.disabled:hover .list-group-item-text,
#vlocity .list-group-item.disabled:focus .list-group-item-text {
  color: #777;
}
#vlocity .list-group-item.active,
#vlocity .list-group-item.active:hover,
#vlocity .list-group-item.active:focus {
  z-index: 2;
  color: #fff;
  background-color: #337ab7;
  border-color: #337ab7;
}
#vlocity .list-group-item.active .list-group-item-heading,
#vlocity .list-group-item.active:hover .list-group-item-heading,
#vlocity .list-group-item.active:focus .list-group-item-heading,
#vlocity .list-group-item.active .list-group-item-heading > small,
#vlocity .list-group-item.active:hover .list-group-item-heading > small,
#vlocity .list-group-item.active:focus .list-group-item-heading > small,
#vlocity .list-group-item.active .list-group-item-heading > .small,
#vlocity .list-group-item.active:hover .list-group-item-heading > .small,
#vlocity .list-group-item.active:focus .list-group-item-heading > .small {
  color: inherit;
}
#vlocity .list-group-item.active .list-group-item-text,
#vlocity .list-group-item.active:hover .list-group-item-text,
#vlocity .list-group-item.active:focus .list-group-item-text {
  color: #c7ddef;
}
#vlocity .list-group-item-success {
  color: #3c763d;
  background-color: #dff0d8;
}
#vlocity a.list-group-item-success {
  color: #3c763d;
}
#vlocity a.list-group-item-success .list-group-item-heading {
  color: inherit;
}
#vlocity a.list-group-item-success:hover,
#vlocity a.list-group-item-success:focus {
  color: #3c763d;
  background-color: #d0e9c6;
}
#vlocity a.list-group-item-success.active,
#vlocity a.list-group-item-success.active:hover,
#vlocity a.list-group-item-success.active:focus {
  color: #fff;
  background-color: #3c763d;
  border-color: #3c763d;
}
#vlocity .list-group-item-info {
  color: #31708f;
  background-color: #d9edf7;
}
#vlocity a.list-group-item-info {
  color: #31708f;
}
#vlocity a.list-group-item-info .list-group-item-heading {
  color: inherit;
}
#vlocity a.list-group-item-info:hover,
#vlocity a.list-group-item-info:focus {
  color: #31708f;
  background-color: #c4e3f3;
}
#vlocity a.list-group-item-info.active,
#vlocity a.list-group-item-info.active:hover,
#vlocity a.list-group-item-info.active:focus {
  color: #fff;
  background-color: #31708f;
  border-color: #31708f;
}
#vlocity .list-group-item-warning {
  color: #8a6d3b;
  background-color: #fcf8e3;
}
#vlocity a.list-group-item-warning {
  color: #8a6d3b;
}
#vlocity a.list-group-item-warning .list-group-item-heading {
  color: inherit;
}
#vlocity a.list-group-item-warning:hover,
#vlocity a.list-group-item-warning:focus {
  color: #8a6d3b;
  background-color: #faf2cc;
}
#vlocity a.list-group-item-warning.active,
#vlocity a.list-group-item-warning.active:hover,
#vlocity a.list-group-item-warning.active:focus {
  color: #fff;
  background-color: #8a6d3b;
  border-color: #8a6d3b;
}
#vlocity .list-group-item-danger {
  color: #a94442;
  background-color: #f2dede;
}
#vlocity a.list-group-item-danger {
  color: #a94442;
}
#vlocity a.list-group-item-danger .list-group-item-heading {
  color: inherit;
}
#vlocity a.list-group-item-danger:hover,
#vlocity a.list-group-item-danger:focus {
  color: #a94442;
  background-color: #ebcccc;
}
#vlocity a.list-group-item-danger.active,
#vlocity a.list-group-item-danger.active:hover,
#vlocity a.list-group-item-danger.active:focus {
  color: #fff;
  background-color: #a94442;
  border-color: #a94442;
}
#vlocity .list-group-item-heading {
  margin-top: 0;
  margin-bottom: 5px;
}
#vlocity .list-group-item-text {
  margin-bottom: 0;
  line-height: 1.3;
}
#vlocity .panel {
  margin-bottom: 20px;
  background-color: #fff;
  border: 1px solid transparent;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
}
#vlocity .panel-body {
  padding: 15px;
}
#vlocity .panel-heading {
  padding: 10px 15px;
  border-bottom: 1px solid transparent;
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
#vlocity .panel-heading > .dropdown .dropdown-toggle {
  color: inherit;
}
#vlocity .panel-title {
  margin-top: 0;
  margin-bottom: 0;
  font-size: 16px;
  color: inherit;
}
#vlocity .panel-title > a {
  color: inherit;
}
#vlocity .panel-footer {
  padding: 10px 15px;
  background-color: #f5f5f5;
  border-top: 1px solid #ddd;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
#vlocity .panel > .list-group,
#vlocity .panel > .panel-collapse > .list-group {
  margin-bottom: 0;
}
#vlocity .panel > .list-group .list-group-item,
#vlocity .panel > .panel-collapse > .list-group .list-group-item {
  border-width: 1px 0;
  border-radius: 0;
}
#vlocity .panel > .list-group:first-child .list-group-item:first-child,
#vlocity .panel > .panel-collapse > .list-group:first-child .list-group-item:first-child {
  border-top: 0;
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
#vlocity .panel > .list-group:last-child .list-group-item:last-child,
#vlocity .panel > .panel-collapse > .list-group:last-child .list-group-item:last-child {
  border-bottom: 0;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
#vlocity .panel-heading + .list-group .list-group-item:first-child {
  border-top-width: 0;
}
#vlocity .list-group + .panel-footer {
  border-top-width: 0;
}
#vlocity .panel > .table,
#vlocity .panel > .table-responsive > .table,
#vlocity .panel > .panel-collapse > .table {
  margin-bottom: 0;
}
#vlocity .panel > .table caption,
#vlocity .panel > .table-responsive > .table caption,
#vlocity .panel > .panel-collapse > .table caption {
  padding-right: 15px;
  padding-left: 15px;
}
#vlocity .panel > .table:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child {
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
#vlocity .panel > .table:first-child > thead:first-child > tr:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child,
#vlocity .panel > .table:first-child > tbody:first-child > tr:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child {
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
#vlocity .panel > .table:first-child > thead:first-child > tr:first-child td:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child td:first-child,
#vlocity .panel > .table:first-child > tbody:first-child > tr:first-child td:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child td:first-child,
#vlocity .panel > .table:first-child > thead:first-child > tr:first-child th:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child th:first-child,
#vlocity .panel > .table:first-child > tbody:first-child > tr:first-child th:first-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child th:first-child {
  border-top-left-radius: 3px;
}
#vlocity .panel > .table:first-child > thead:first-child > tr:first-child td:last-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child td:last-child,
#vlocity .panel > .table:first-child > tbody:first-child > tr:first-child td:last-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child td:last-child,
#vlocity .panel > .table:first-child > thead:first-child > tr:first-child th:last-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child th:last-child,
#vlocity .panel > .table:first-child > tbody:first-child > tr:first-child th:last-child,
#vlocity .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child th:last-child {
  border-top-right-radius: 3px;
}
#vlocity .panel > .table:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child {
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
#vlocity .panel > .table:last-child > tbody:last-child > tr:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child,
#vlocity .panel > .table:last-child > tfoot:last-child > tr:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child {
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
#vlocity .panel > .table:last-child > tbody:last-child > tr:last-child td:first-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child td:first-child,
#vlocity .panel > .table:last-child > tfoot:last-child > tr:last-child td:first-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child td:first-child,
#vlocity .panel > .table:last-child > tbody:last-child > tr:last-child th:first-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child th:first-child,
#vlocity .panel > .table:last-child > tfoot:last-child > tr:last-child th:first-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child th:first-child {
  border-bottom-left-radius: 3px;
}
#vlocity .panel > .table:last-child > tbody:last-child > tr:last-child td:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child td:last-child,
#vlocity .panel > .table:last-child > tfoot:last-child > tr:last-child td:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child td:last-child,
#vlocity .panel > .table:last-child > tbody:last-child > tr:last-child th:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child th:last-child,
#vlocity .panel > .table:last-child > tfoot:last-child > tr:last-child th:last-child,
#vlocity .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child th:last-child {
  border-bottom-right-radius: 3px;
}
#vlocity .panel > .panel-body + .table,
#vlocity .panel > .panel-body + .table-responsive,
#vlocity .panel > .table + .panel-body,
#vlocity .panel > .table-responsive + .panel-body {
  border-top: 1px solid #ddd;
}
#vlocity .panel > .table > tbody:first-child > tr:first-child th,
#vlocity .panel > .table > tbody:first-child > tr:first-child td {
  border-top: 0;
}
#vlocity .panel > .table-bordered,
#vlocity .panel > .table-responsive > .table-bordered {
  border: 0;
}
#vlocity .panel > .table-bordered > thead > tr > th:first-child,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr > th:first-child,
#vlocity .panel > .table-bordered > tbody > tr > th:first-child,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr > th:first-child,
#vlocity .panel > .table-bordered > tfoot > tr > th:first-child,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr > th:first-child,
#vlocity .panel > .table-bordered > thead > tr > td:first-child,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr > td:first-child,
#vlocity .panel > .table-bordered > tbody > tr > td:first-child,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr > td:first-child,
#vlocity .panel > .table-bordered > tfoot > tr > td:first-child,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr > td:first-child {
  border-left: 0;
}
#vlocity .panel > .table-bordered > thead > tr > th:last-child,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr > th:last-child,
#vlocity .panel > .table-bordered > tbody > tr > th:last-child,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr > th:last-child,
#vlocity .panel > .table-bordered > tfoot > tr > th:last-child,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr > th:last-child,
#vlocity .panel > .table-bordered > thead > tr > td:last-child,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr > td:last-child,
#vlocity .panel > .table-bordered > tbody > tr > td:last-child,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr > td:last-child,
#vlocity .panel > .table-bordered > tfoot > tr > td:last-child,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr > td:last-child {
  border-right: 0;
}
#vlocity .panel > .table-bordered > thead > tr:first-child > td,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr:first-child > td,
#vlocity .panel > .table-bordered > tbody > tr:first-child > td,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr:first-child > td,
#vlocity .panel > .table-bordered > thead > tr:first-child > th,
#vlocity .panel > .table-responsive > .table-bordered > thead > tr:first-child > th,
#vlocity .panel > .table-bordered > tbody > tr:first-child > th,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr:first-child > th {
  border-bottom: 0;
}
#vlocity .panel > .table-bordered > tbody > tr:last-child > td,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr:last-child > td,
#vlocity .panel > .table-bordered > tfoot > tr:last-child > td,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr:last-child > td,
#vlocity .panel > .table-bordered > tbody > tr:last-child > th,
#vlocity .panel > .table-responsive > .table-bordered > tbody > tr:last-child > th,
#vlocity .panel > .table-bordered > tfoot > tr:last-child > th,
#vlocity .panel > .table-responsive > .table-bordered > tfoot > tr:last-child > th {
  border-bottom: 0;
}
#vlocity .panel > .table-responsive {
  margin-bottom: 0;
  border: 0;
}
#vlocity .panel-group {
  margin-bottom: 20px;
}
#vlocity .panel-group .panel {
  margin-bottom: 0;
  border-radius: 4px;
}
#vlocity .panel-group .panel + .panel {
  margin-top: 5px;
}
#vlocity .panel-group .panel-heading {
  border-bottom: 0;
}
#vlocity .panel-group .panel-heading + .panel-collapse > .panel-body,
#vlocity .panel-group .panel-heading + .panel-collapse > .list-group {
  border-top: 1px solid #ddd;
}
#vlocity .panel-group .panel-footer {
  border-top: 0;
}
#vlocity .panel-group .panel-footer + .panel-collapse .panel-body {
  border-bottom: 1px solid #ddd;
}
#vlocity .panel-default {
  border-color: #ddd;
}
#vlocity .panel-default > .panel-heading {
  color: #333;
  background-color: #f5f5f5;
  border-color: #ddd;
}
#vlocity .panel-default > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #ddd;
}
#vlocity .panel-default > .panel-heading .badge {
  color: #f5f5f5;
  background-color: #333;
}
#vlocity .panel-default > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #ddd;
}
#vlocity .panel-primary {
  border-color: #337ab7;
}
#vlocity .panel-primary > .panel-heading {
  color: #fff;
  background-color: #337ab7;
  border-color: #337ab7;
}
#vlocity .panel-primary > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #337ab7;
}
#vlocity .panel-primary > .panel-heading .badge {
  color: #337ab7;
  background-color: #fff;
}
#vlocity .panel-primary > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #337ab7;
}
#vlocity .panel-success {
  border-color: #d6e9c6;
}
#vlocity .panel-success > .panel-heading {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
#vlocity .panel-success > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #d6e9c6;
}
#vlocity .panel-success > .panel-heading .badge {
  color: #dff0d8;
  background-color: #3c763d;
}
#vlocity .panel-success > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #d6e9c6;
}
#vlocity .panel-info {
  border-color: #bce8f1;
}
#vlocity .panel-info > .panel-heading {
  color: #31708f;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
#vlocity .panel-info > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #bce8f1;
}
#vlocity .panel-info > .panel-heading .badge {
  color: #d9edf7;
  background-color: #31708f;
}
#vlocity .panel-info > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #bce8f1;
}
#vlocity .panel-warning {
  border-color: #faebcc;
}
#vlocity .panel-warning > .panel-heading {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}
#vlocity .panel-warning > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #faebcc;
}
#vlocity .panel-warning > .panel-heading .badge {
  color: #fcf8e3;
  background-color: #8a6d3b;
}
#vlocity .panel-warning > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #faebcc;
}
#vlocity .panel-danger {
  border-color: #ebccd1;
}
#vlocity .panel-danger > .panel-heading {
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}
#vlocity .panel-danger > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #ebccd1;
}
#vlocity .panel-danger > .panel-heading .badge {
  color: #f2dede;
  background-color: #a94442;
}
#vlocity .panel-danger > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #ebccd1;
}
#vlocity .embed-responsive {
  position: relative;
  display: block;
  height: 0;
  padding: 0;
  overflow: hidden;
}
#vlocity .embed-responsive .embed-responsive-item,
#vlocity .embed-responsive iframe,
#vlocity .embed-responsive embed,
#vlocity .embed-responsive object,
#vlocity .embed-responsive video {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
#vlocity .embed-responsive.embed-responsive-16by9 {
  padding-bottom: 56.25%;
}
#vlocity .embed-responsive.embed-responsive-4by3 {
  padding-bottom: 75%;
}
#vlocity .well {
  min-height: 20px;
  padding: 19px;
  margin-bottom: 20px;
  background-color: #f5f5f5;
  border: 1px solid #e3e3e3;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}
#vlocity .well blockquote {
  border-color: #ddd;
  border-color: rgba(0, 0, 0, 0.15);
}
#vlocity .well-lg {
  padding: 24px;
  border-radius: 6px;
}
#vlocity .well-sm {
  padding: 9px;
  border-radius: 3px;
}
#vlocity .close {
  float: right;
  font-size: 21px;
  font-weight: bold;
  line-height: 1;
  color: #000;
  text-shadow: 0 1px 0 #fff;
  filter: alpha(opacity=20);
  opacity: .2;
}
#vlocity .close:hover,
#vlocity .close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
  filter: alpha(opacity=50);
  opacity: .5;
}
#vlocity button.close {
  -webkit-appearance: none;
  padding: 0;
  cursor: pointer;
  background: transparent;
  border: 0;
}
#vlocity .modal-open {
  overflow: hidden;
}
#vlocity .modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  display: none;
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
#vlocity .modal.fade .modal-dialog {
  -webkit-transition: -webkit-transform 0.3s ease-out;
  -o-transition: -o-transform 0.3s ease-out;
  transition: transform 0.3s ease-out;
  -webkit-transform: translate(0, -25%);
  -ms-transform: translate(0, -25%);
  -o-transform: translate(0, -25%);
  transform: translate(0, -25%);
}
#vlocity .modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}
#vlocity .modal-open .modal {
  overflow-x: hidden;
  overflow-y: auto;
}
#vlocity .modal-dialog {
  position: relative;
  width: auto;
  margin: 10px;
}
#vlocity .modal-content {
  position: relative;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #999;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 6px;
  outline: 0;
  -webkit-box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
  box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
}
#vlocity .modal-backdrop {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  background-color: #000;
}
#vlocity .modal-backdrop.fade {
  filter: alpha(opacity=0);
  opacity: 0;
}
#vlocity .modal-backdrop.in {
  filter: alpha(opacity=50);
  opacity: .5;
}
#vlocity .modal-header {
  min-height: 16.42857143px;
  padding: 15px;
  border-bottom: 1px solid #e5e5e5;
}
#vlocity .modal-header .close {
  margin-top: -2px;
}
#vlocity .modal-title {
  margin: 0;
  line-height: 1.42857143;
}
#vlocity .modal-body {
  position: relative;
  padding: 15px;
}
#vlocity .modal-footer {
  padding: 15px;
  text-align: right;
  border-top: 1px solid #e5e5e5;
}
#vlocity .modal-footer .btn + .btn {
  margin-bottom: 0;
  margin-left: 5px;
}
#vlocity .modal-footer .btn-group .btn + .btn {
  margin-left: -1px;
}
#vlocity .modal-footer .btn-block + .btn-block {
  margin-left: 0;
}
#vlocity .modal-scrollbar-measure {
  position: absolute;
  top: -9999px;
  width: 50px;
  height: 50px;
  overflow: scroll;
}
@media (min-width: 768px) {
  #vlocity .modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
  #vlocity .modal-content {
    -webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
  }
  #vlocity .modal-sm {
    width: 300px;
  }
}
@media (min-width: 992px) {
  #vlocity .modal-lg {
    width: 900px;
  }
}
#vlocity .tooltip {
  position: absolute;
  z-index: 1070;
  display: block;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 12px;
  font-weight: normal;
  line-height: 1.4;
  visibility: visible;
  filter: alpha(opacity=0);
  opacity: 0;
}
#vlocity .tooltip.in {
  filter: alpha(opacity=90);
  opacity: .9;
}
#vlocity .tooltip.top {
  padding: 5px 0;
  margin-top: -3px;
}
#vlocity .tooltip.right {
  padding: 0 5px;
  margin-left: 3px;
}
#vlocity .tooltip.bottom {
  padding: 5px 0;
  margin-top: 3px;
}
#vlocity .tooltip.left {
  padding: 0 5px;
  margin-left: -3px;
}
#vlocity .tooltip-inner {
  max-width: 200px;
  padding: 3px 8px;
  color: #fff;
  text-align: center;
  text-decoration: none;
  background-color: #000;
  border-radius: 4px;
}
#vlocity .tooltip-arrow {
  position: absolute;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}
#vlocity .tooltip.top .tooltip-arrow {
  bottom: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
#vlocity .tooltip.top-left .tooltip-arrow {
  right: 5px;
  bottom: 0;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
#vlocity .tooltip.top-right .tooltip-arrow {
  bottom: 0;
  left: 5px;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
#vlocity .tooltip.right .tooltip-arrow {
  top: 50%;
  left: 0;
  margin-top: -5px;
  border-width: 5px 5px 5px 0;
  border-right-color: #000;
}
#vlocity .tooltip.left .tooltip-arrow {
  top: 50%;
  right: 0;
  margin-top: -5px;
  border-width: 5px 0 5px 5px;
  border-left-color: #000;
}
#vlocity .tooltip.bottom .tooltip-arrow {
  top: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
#vlocity .tooltip.bottom-left .tooltip-arrow {
  top: 0;
  right: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
#vlocity .tooltip.bottom-right .tooltip-arrow {
  top: 0;
  left: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
#vlocity .popover {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1060;
  display: none;
  max-width: 276px;
  padding: 1px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857143;
  text-align: left;
  white-space: normal;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 6px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
}
#vlocity .popover.top {
  margin-top: -10px;
}
#vlocity .popover.right {
  margin-left: 10px;
}
#vlocity .popover.bottom {
  margin-top: 10px;
}
#vlocity .popover.left {
  margin-left: -10px;
}
#vlocity .popover-title {
  padding: 8px 14px;
  margin: 0;
  font-size: 14px;
  background-color: #f7f7f7;
  border-bottom: 1px solid #ebebeb;
  border-radius: 5px 5px 0 0;
}
#vlocity .popover-content {
  padding: 9px 14px;
}
#vlocity .popover > .arrow,
#vlocity .popover > .arrow:after {
  position: absolute;
  display: block;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}
#vlocity .popover > .arrow {
  border-width: 11px;
}
#vlocity .popover > .arrow:after {
  content: "";
  border-width: 10px;
}
#vlocity .popover.top > .arrow {
  bottom: -11px;
  left: 50%;
  margin-left: -11px;
  border-top-color: #999;
  border-top-color: rgba(0, 0, 0, 0.25);
  border-bottom-width: 0;
}
#vlocity .popover.top > .arrow:after {
  bottom: 1px;
  margin-left: -10px;
  content: " ";
  border-top-color: #fff;
  border-bottom-width: 0;
}
#vlocity .popover.right > .arrow {
  top: 50%;
  left: -11px;
  margin-top: -11px;
  border-right-color: #999;
  border-right-color: rgba(0, 0, 0, 0.25);
  border-left-width: 0;
}
#vlocity .popover.right > .arrow:after {
  bottom: -10px;
  left: 1px;
  content: " ";
  border-right-color: #fff;
  border-left-width: 0;
}
#vlocity .popover.bottom > .arrow {
  top: -11px;
  left: 50%;
  margin-left: -11px;
  border-top-width: 0;
  border-bottom-color: #999;
  border-bottom-color: rgba(0, 0, 0, 0.25);
}
#vlocity .popover.bottom > .arrow:after {
  top: 1px;
  margin-left: -10px;
  content: " ";
  border-top-width: 0;
  border-bottom-color: #fff;
}
#vlocity .popover.left > .arrow {
  top: 50%;
  right: -11px;
  margin-top: -11px;
  border-right-width: 0;
  border-left-color: #999;
  border-left-color: rgba(0, 0, 0, 0.25);
}
#vlocity .popover.left > .arrow:after {
  right: 1px;
  bottom: -10px;
  content: " ";
  border-right-width: 0;
  border-left-color: #fff;
}
#vlocity .carousel {
  position: relative;
}
#vlocity .carousel-inner {
  position: relative;
  width: 100%;
  overflow: hidden;
}
#vlocity .carousel-inner > .item {
  position: relative;
  display: none;
  -webkit-transition: 0.6s ease-in-out left;
  -o-transition: 0.6s ease-in-out left;
  transition: 0.6s ease-in-out left;
}
#vlocity .carousel-inner > .item > img,
#vlocity .carousel-inner > .item > a > img {
  line-height: 1;
}
@media all and (transform-3d), (-webkit-transform-3d) {
  #vlocity .carousel-inner > .item {
    -webkit-transition: -webkit-transform 0.6s ease-in-out;
    -o-transition: -o-transform 0.6s ease-in-out;
    transition: transform 0.6s ease-in-out;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-perspective: 1000;
    perspective: 1000;
  }
  #vlocity .carousel-inner > .item.next,
  #vlocity .carousel-inner > .item.active.right {
    left: 0;
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
  }
  #vlocity .carousel-inner > .item.prev,
  #vlocity .carousel-inner > .item.active.left {
    left: 0;
    -webkit-transform: translate3d(-100%, 0, 0);
    transform: translate3d(-100%, 0, 0);
  }
  #vlocity .carousel-inner > .item.next.left,
  #vlocity .carousel-inner > .item.prev.right,
  #vlocity .carousel-inner > .item.active {
    left: 0;
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}
#vlocity .carousel-inner > .active,
#vlocity .carousel-inner > .next,
#vlocity .carousel-inner > .prev {
  display: block;
}
#vlocity .carousel-inner > .active {
  left: 0;
}
#vlocity .carousel-inner > .next,
#vlocity .carousel-inner > .prev {
  position: absolute;
  top: 0;
  width: 100%;
}
#vlocity .carousel-inner > .next {
  left: 100%;
}
#vlocity .carousel-inner > .prev {
  left: -100%;
}
#vlocity .carousel-inner > .next.left,
#vlocity .carousel-inner > .prev.right {
  left: 0;
}
#vlocity .carousel-inner > .active.left {
  left: -100%;
}
#vlocity .carousel-inner > .active.right {
  left: 100%;
}
#vlocity .carousel-control {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 15%;
  font-size: 20px;
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.6);
  filter: alpha(opacity=50);
  opacity: .5;
}
#vlocity .carousel-control.left {
  background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  background-image: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0.5)), to(rgba(0, 0, 0, 0.0001)));
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1);
  background-repeat: repeat-x;
}
#vlocity .carousel-control.right {
  right: 0;
  left: auto;
  background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  background-image: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0.0001)), to(rgba(0, 0, 0, 0.5)));
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);
  background-repeat: repeat-x;
}
#vlocity .carousel-control:hover,
#vlocity .carousel-control:focus {
  color: #fff;
  text-decoration: none;
  filter: alpha(opacity=90);
  outline: 0;
  opacity: .9;
}
#vlocity .carousel-control .icon-prev,
#vlocity .carousel-control .icon-next,
#vlocity .carousel-control .glyphicon-chevron-left,
#vlocity .carousel-control .glyphicon-chevron-right {
  position: absolute;
  top: 50%;
  z-index: 5;
  display: inline-block;
}
#vlocity .carousel-control .icon-prev,
#vlocity .carousel-control .glyphicon-chevron-left {
  left: 50%;
  margin-left: -10px;
}
#vlocity .carousel-control .icon-next,
#vlocity .carousel-control .glyphicon-chevron-right {
  right: 50%;
  margin-right: -10px;
}
#vlocity .carousel-control .icon-prev,
#vlocity .carousel-control .icon-next {
  width: 20px;
  height: 20px;
  margin-top: -10px;
  font-family: serif;
}
#vlocity .carousel-control .icon-prev:before {
  content: '\2039';
}
#vlocity .carousel-control .icon-next:before {
  content: '\203a';
}
#vlocity .carousel-indicators {
  position: absolute;
  bottom: 10px;
  left: 50%;
  z-index: 15;
  width: 60%;
  padding-left: 0;
  margin-left: -30%;
  text-align: center;
  list-style: none;
}
#vlocity .carousel-indicators li {
  display: inline-block;
  width: 10px;
  height: 10px;
  margin: 1px;
  text-indent: -999px;
  cursor: pointer;
  background-color: #000 \9;
  background-color: rgba(0, 0, 0, 0);
  border: 1px solid #fff;
  border-radius: 10px;
}
#vlocity .carousel-indicators .active {
  width: 12px;
  height: 12px;
  margin: 0;
  background-color: #fff;
}
#vlocity .carousel-caption {
  position: absolute;
  right: 15%;
  bottom: 20px;
  left: 15%;
  z-index: 10;
  padding-top: 20px;
  padding-bottom: 20px;
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.6);
}
#vlocity .carousel-caption .btn {
  text-shadow: none;
}
@media screen and (min-width: 768px) {
  #vlocity .carousel-control .glyphicon-chevron-left,
  #vlocity .carousel-control .glyphicon-chevron-right,
  #vlocity .carousel-control .icon-prev,
  #vlocity .carousel-control .icon-next {
    width: 30px;
    height: 30px;
    margin-top: -15px;
    font-size: 30px;
  }
  #vlocity .carousel-control .glyphicon-chevron-left,
  #vlocity .carousel-control .icon-prev {
    margin-left: -15px;
  }
  #vlocity .carousel-control .glyphicon-chevron-right,
  #vlocity .carousel-control .icon-next {
    margin-right: -15px;
  }
  #vlocity .carousel-caption {
    right: 20%;
    left: 20%;
    padding-bottom: 30px;
  }
  #vlocity .carousel-indicators {
    bottom: 20px;
  }
}
#vlocity .clearfix:before,
#vlocity .clearfix:after,
#vlocity .dl-horizontal dd:before,
#vlocity .dl-horizontal dd:after,
#vlocity .container:before,
#vlocity .container:after,
#vlocity .container-fluid:before,
#vlocity .container-fluid:after,
#vlocity .row:before,
#vlocity .row:after,
#vlocity .form-horizontal .form-group:before,
#vlocity .form-horizontal .form-group:after,
#vlocity .btn-toolbar:before,
#vlocity .btn-toolbar:after,
#vlocity .btn-group-vertical > .btn-group:before,
#vlocity .btn-group-vertical > .btn-group:after,
#vlocity .nav:before,
#vlocity .nav:after,
#vlocity .navbar:before,
#vlocity .navbar:after,
#vlocity .navbar-header:before,
#vlocity .navbar-header:after,
#vlocity .navbar-collapse:before,
#vlocity .navbar-collapse:after,
#vlocity .pager:before,
#vlocity .pager:after,
#vlocity .panel-body:before,
#vlocity .panel-body:after,
#vlocity .modal-footer:before,
#vlocity .modal-footer:after {
  display: table;
  content: " ";
}
#vlocity .clearfix:after,
#vlocity .dl-horizontal dd:after,
#vlocity .container:after,
#vlocity .container-fluid:after,
#vlocity .row:after,
#vlocity .form-horizontal .form-group:after,
#vlocity .btn-toolbar:after,
#vlocity .btn-group-vertical > .btn-group:after,
#vlocity .nav:after,
#vlocity .navbar:after,
#vlocity .navbar-header:after,
#vlocity .navbar-collapse:after,
#vlocity .pager:after,
#vlocity .panel-body:after,
#vlocity .modal-footer:after {
  clear: both;
}
#vlocity .center-block {
  display: block;
  margin-right: auto;
  margin-left: auto;
}
#vlocity .pull-right {
  float: right !important;
}
#vlocity .pull-left {
  float: left !important;
}
#vlocity .hide {
  display: none !important;
}
#vlocity .show {
  display: block !important;
}
#vlocity .invisible {
  visibility: hidden;
}
#vlocity .text-hide {
  font: 0/0 a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}
#vlocity .hidden {
  display: none !important;
  visibility: hidden !important;
}
#vlocity .affix {
  position: fixed;
}
@-ms-viewport {
  width: device-width;
}
#vlocity .visible-xs,
#vlocity .visible-sm,
#vlocity .visible-md,
#vlocity .visible-lg {
  display: none !important;
}
#vlocity .visible-xs-block,
#vlocity .visible-xs-inline,
#vlocity .visible-xs-inline-block,
#vlocity .visible-sm-block,
#vlocity .visible-sm-inline,
#vlocity .visible-sm-inline-block,
#vlocity .visible-md-block,
#vlocity .visible-md-inline,
#vlocity .visible-md-inline-block,
#vlocity .visible-lg-block,
#vlocity .visible-lg-inline,
#vlocity .visible-lg-inline-block {
  display: none !important;
}
@media (max-width: 767px) {
  #vlocity .visible-xs {
    display: block !important;
  }
  #vlocity table.visible-xs {
    display: table;
  }
  #vlocity tr.visible-xs {
    display: table-row !important;
  }
  #vlocity th.visible-xs,
  #vlocity td.visible-xs {
    display: table-cell !important;
  }
}
@media (max-width: 767px) {
  #vlocity .visible-xs-block {
    display: block !important;
  }
}
@media (max-width: 767px) {
  #vlocity .visible-xs-inline {
    display: inline !important;
  }
}
@media (max-width: 767px) {
  #vlocity .visible-xs-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  #vlocity .visible-sm {
    display: block !important;
  }
  #vlocity table.visible-sm {
    display: table;
  }
  #vlocity tr.visible-sm {
    display: table-row !important;
  }
  #vlocity th.visible-sm,
  #vlocity td.visible-sm {
    display: table-cell !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  #vlocity .visible-sm-block {
    display: block !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  #vlocity .visible-sm-inline {
    display: inline !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  #vlocity .visible-sm-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  #vlocity .visible-md {
    display: block !important;
  }
  #vlocity table.visible-md {
    display: table;
  }
  #vlocity tr.visible-md {
    display: table-row !important;
  }
  #vlocity th.visible-md,
  #vlocity td.visible-md {
    display: table-cell !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  #vlocity .visible-md-block {
    display: block !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  #vlocity .visible-md-inline {
    display: inline !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  #vlocity .visible-md-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 1200px) {
  #vlocity .visible-lg {
    display: block !important;
  }
  #vlocity table.visible-lg {
    display: table;
  }
  #vlocity tr.visible-lg {
    display: table-row !important;
  }
  #vlocity th.visible-lg,
  #vlocity td.visible-lg {
    display: table-cell !important;
  }
}
@media (min-width: 1200px) {
  #vlocity .visible-lg-block {
    display: block !important;
  }
}
@media (min-width: 1200px) {
  #vlocity .visible-lg-inline {
    display: inline !important;
  }
}
@media (min-width: 1200px) {
  #vlocity .visible-lg-inline-block {
    display: inline-block !important;
  }
}
@media (max-width: 767px) {
  #vlocity .hidden-xs {
    display: none !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  #vlocity .hidden-sm {
    display: none !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  #vlocity .hidden-md {
    display: none !important;
  }
}
@media (min-width: 1200px) {
  #vlocity .hidden-lg {
    display: none !important;
  }
}
#vlocity .visible-print {
  display: none !important;
}
@media print {
  #vlocity .visible-print {
    display: block !important;
  }
  #vlocity table.visible-print {
    display: table;
  }
  #vlocity tr.visible-print {
    display: table-row !important;
  }
  #vlocity th.visible-print,
  #vlocity td.visible-print {
    display: table-cell !important;
  }
}
#vlocity .visible-print-block {
  display: none !important;
}
@media print {
  #vlocity .visible-print-block {
    display: block !important;
  }
}
#vlocity .visible-print-inline {
  display: none !important;
}
@media print {
  #vlocity .visible-print-inline {
    display: inline !important;
  }
}
#vlocity .visible-print-inline-block {
  display: none !important;
}
@media print {
  #vlocity .visible-print-inline-block {
    display: inline-block !important;
  }
}
@media print {
  #vlocity .hidden-print {
    display: none !important;
  }
}


/*ADDED STYLE*/

#vlocity .panel-default > .panel-heading {
background-color: #e5e5e5 !important;
padding: 3px 10px 7px 25px;
border-top-left-radius: 3px;
border-top-right-radius: 3px;
border: 1px solid #e5e5e5 !important;
border-bottom: none !important;
}

#vlocity .vlc-step-circle {
height: 22px !important;
width: 22px !important;
font-size: 15px !important;
text-align: center !important;
padding: 0 !important;
line-height: 22px;
background-color: #e5e5e5 !important;
}


/*--------------

Active (add class to "panel-heading")*/

#vlocity .panel-default.active > .panel-heading {

border-bottom-left-radius: 0px;
border-bottom-right-radius: 0px;
background-color: #05a6df !important;
border: 1px solid #05a6df !important;

}

#vlocity .panel-default.active .vlc-step-circle {
background-color: #05a6df !important;
}

#vlocity .active .panel-collapse.collapse.in .panel-body {
border-bottom-left-radius: 3px;
border-bottom-right-radius: 3px;
}
#vlocity .vlc-toggle {
    font-size: 17px !important
}

#vlocity .panel-default {
    border: none !important;
}

#vlocity .panel-group .panel {
    margin-top: 8px
}

#vlocity .panel-default > .panel-heading + .panel-collapse > .panel-body {
    border: 1px solid rgba(0,0,0,.15) !important;
    border-top: none !important;
}

#vlocity label {
    font-weight: normal;
    font-size: 13px !important;
}

#vlocity .vlc-block-heading {
    padding: 10px;
    font-size: 20px;
    color: rgba(0,0,0,.95);
    font: 17px Arial;
    border-bottom: 1px solid #dedede;
    margin-bottom: 22px;
}

#vlocity .panel-body {
  background-color: #f8f8f8;
}

#vlocity .panel-body {
  background-color: #f8f8f8;
}
body {
    font-size: 12px;
}
 .zen .zen-tabMenu a {
    font-size: 13px !important;
}
 h2 {
    font-size: 12px !important;
    font-weight: bold !important;
}
 #sidebarDiv .sidebarModuleHeader h2.brandPrimaryFgr {
    margin-bottom: 0px;
}
 .mruItem a span {
    font-size: 12px;
    color: #333435;
    text-decoration: underline;
}
 .recycleBinModule div a img {
    vertical-align: baseline;
}
 .recycleBinModule div a span {
    font-size: 12px;
}
 img {
    vertical-align: baseline;
}
 .navLinks a, #userNavLabel {
    font-size: 11px !important;
}
 .well blockquote {
    border-color: #ddd;
    border-color: rgba(0, 0, 0, 0.15);
}
 .panel-heading .badge {
    margin-top: 5px;
}
 .panel-body textarea {
    width: 480px;
    height: 94px;
    padding: 11px;
    width: 480px;
    border: 1px solid #d9d9d9;
    border-radius: 4px;
    color: #8a8a8a;
    padding: 0px;
    background-color: white;
}
 .panel-group .panel {
    margin-bottom: 15px;
}
 .accordion-toggle:hover {
    cursor: pointer;
    text-decoration: none;
}
 .accordion-toggle .glyphicon {
    position: absolute;
    top: 12px;
    right: 0px;
}
 .panel-heading {
    background-color: #1797C0 !important;
    border-color: #1797C0 !important;
    color: white !important;
}
 .accordion-toggle i {
    color: #c4c4c4;
}
 .panel-body .button-container {
    float: right;
    margin-top: 16px;
}
 .panel-body .form-group {
    margin-top: 10px;
}
 .panel-body .form-group .form-group {
    margin-bottom: 15px;
    float: left;
    width: 46%;
    margin-right: 5px;
    margin-top: 0px;
}
 .panel-body .form-group label {
    float: left;
    display: block;
    width: 100%;
}
 .button-container .vlocity-assessment-save-button {
    background-color: #0078a4;
    color: #fff;
    text-transform: capitalize;
    border: none;
}
 .button-container .vlocity-assessment-save-button:hover {
    background-color: #006A91;
}
 .selectize-dropdown {
    margin: -5px 0 0 0 !important;
}
 .help-text {
    height: 15px;
    color: #737373;
}
 td.data-cell {
    padding: 0px !important;
    margin: 0px !important;
}
 input.data-input {
    width: 100%;
    height: 100%;
    margin: 0px;
    border: none;
    height: 34px;
    font-family: inherit;
    font-size: 14px;
    padding-left: 20px}
 .border-clear {
    border-style: hidden !important }
}

 .vlc-handwriting {
    font-family: cursive !important;
}
 .vlc-sub-block {
    min-height: 35px;
    color: rgba(255, 0, 0, 0.72);
}
 i.vlc-plus {
    color: rgba(23, 151, 192, 0.72);
    margin-left: 2px;
}
 i.vlc-minus {
    color: rgba(42, 47, 63, 0.73);
    margin-left: 5px;
}
 .panel-heading > .vlc-plus {
    color: white !important;
    margin-left: 5px;
}
 .panel-heading > .vlc-minus {
    color: white !important;
    margin-right: 5px;
}

 .vlc-no-label {
    margin-top: 20px;
}
 .vlc-checkbox-ele {
    padding-top: 24px;
}
 .left-inner-addon {
    position: relative;
    width: 100%;
}
 #vlocity .left-inner-addon input {
    padding-left: 30px;
}
 #vlocity .left-inner-addon {
    display: inline-block;
}
 #vlocity .left-inner-addon i {
    position: absolute;
    padding: 10px 12px;
    pointer-events: none;
}
 .dropdown-menu > li {
    margin-right: 1.5em;
}
 textarea {
    z-index: 100;
    position: relative;
    margin-bottom: 20px;
}
 .dropdown-menu {
    z-index: 200;
}
 .range-low {
    display: inline-block;
    padding: 10px;
}
 .range-high {
    display: inline-block;
    padding: 10px;
}
 .vlc-range-input {
    display: inline-block !important;
    width: 80% !important;
}
/* div.vlc-step-heading {
    background-color: #B3B2B2 !important;
    border-color: rgb(240, 240, 240) !important;
}*/
 div.panel-body {
    border: none !important;
    background-color: rgb(240, 240, 240)}
 div.vlc-block-body {
    border: none !important;
    background-color: rgb(240, 240, 240);
    padding: 22px;
}
/* #vlocity .vlc-block-heading {
    background-color: rgb(142, 138, 138) !important;
}*/
#vlocity .block-section {
    padding: 0px !important;
}

#vlocity .panel-heading {
    border: none; 
    border-radius: 0px;
}
#vlocity label {
    font-weight: normal;
    font-size: 16px;
}
#vlocity .accordion-toggle {
    font-size: 24px;
}
.vlc-checkbox-solo {
    margin-left: 5px !important;
    margin-top: 11px !important;
}
.vlc-valid-input {
    color: #58a300;
    font-size: 16px;
    position: absolute;
    right: 20px;
    top: 25px;
}
 .vlc-range-valid-input {
    color: #58a300;
    font-size: 16px;
    position: absolute;
    right: ;
    top: 25px;
}
.vlc-error-input {
    color: #f65327;
    font-size: 16px;
    position: absolute;
    right: 20px;
    top: 25px;
}
.vlc-range-error-input {
    color: #f65327;
    font-size: 16px;
    position: absolute;
    right: ;
    top: 25px;
}
.vlc-valid-input-check {
    color: #58a300;
    font-size: 16px;
    position: relative;
    margin-left: 5px;
}
.vlc-error-input-check {
    color: #f65327;
    font-size: 16px;
    position: relative;
    margin-left: 5px;
}
.vlc-block-heading {
    padding: 20px;
    font-size: 20px;
    color: rgba(0,0,0,.95);
    font: 20px Arial;
    border-bottom: 1px solid #dedede;
    margin-bottom: 22px;
}
.vlc-currency-block {
    display: block !important;
}
.vlc-required-input{
    background-color: #f65327;
    position: absolute;
    left: 16px;
    width: 3px;
    top: 1px;
    bottom: 75px;
}
.vlc-required-input-check{
    background-color: #f65327;
    position: absolute;
    left: 7px;
    width: 3px;
    top: 0px;
    bottom: 69px;
}
.vlc-question-tooltip {
    padding-left: 10px;
    color: #9191a0;
}
.vlc-step-circle {
    width: 32px;
    display: inline-block;
    height: 32px;
    padding-left: 8px;
    padding-top: 3px;
    margin-right: 10px;
    background: #1797C0;
    -moz-border-radius: 50px;
    -webkit-border-radius: 50px;
    border-radius: 33px;
    border: 1px solid white;
}
.vlc-check-label {
    margin-left: 10px;
    font-size: 12px !important;
}
#vlocity .panel-title > a {
    text-decoration: none !important;
    color:  white !important;
}
#vlocity .panel-title > a:hover {
    text-decoration: none !important;
    color: #2a2f3f !important;
}
/*#vlocity input {
    height: 28px/20px !important; 
    line-height: 26px !important;
    text-indent: 10px !important; 
    color: rgba(0,0,0,.4) !important;  
    box-shadow:0 1px 2px rgba(0, 0, 0, 0.3) inset !important; 
    border: 1px solid rgba(0,0,0,.2); border-radius: 3px !important;
}*/
#vlocity .well-lg {
padding: 15px !important;
border-radius: 3px;
}

#vlocity .well-lg hr {
margin-top: 10px;
margin-bottom: 10px;
border: 0;
border-top: 1px solid #eee;
}

#vlocity .well-lg  input[type="checkbox"] {
margin-top: 1px;
padding-top: 0px;
margin-right: 5px !important;
float: left;
}

#vlocity .vlc-disclosure {
margin-top: 0px;
background-color: #dedede;
width: 100%;
}


/*make circle hover too*/
#vlocity .panel-heading .panel-title > a:hover {
text-decoration: none !important;
color: rgba(255, 255, 255, .8) !important;
}



#vlocity .vlc-toggle {font-size: 17px !important}

#vlocity .panel-default {
border: none !important;
}

.vlc-currency{
    padding-top: 3px !important;
}

#vlocity .panel-group .panel {
margin-top: 8px
}


/*
#vlocity .panel-default > .panel-heading + .panel-collapse > .panel-body {
border: 1px solid rgba(0,0,0,.15) !important;
border-top: none !important;
}*/

#vlocity .vlc-block-heading {
padding: 10px;
font-size: 20px;
color: rgba(0,0,0,.95);
font: 17px Arial;
border-bottom: 1px solid #dedede;
margin-bottom: 22px;
}

#vlocity .panel-body {
  background-color: #f8f8f8;
}

#vlocity label {
    display: inline-block;
    max-width: 100%;
}
#vlocity label.active {
    line-height: 14px;
    padding-left: 5px;
    border-left: 3px solid #f65327;
}
.vlc-form-group {
    padding-right: 40px !important;
}

#vlocity .timepicker.dropdown-menu {
  padding: 0 4px;
}
#vlocity .timepicker.dropdown-menu button {
  outline: none;
  border: 0px;
}
#vlocity  .timepicker.dropdown-menu tbody button {
  padding: 6px;
}

#vlocity .datepicker.dropdown-menu {
  width: 250px;
  height: 270px;
}
#vlocity .datepicker.dropdown-menu button {
  outline: none;
  border: 0px;
}
#vlocity .datepicker.dropdown-menu tbody {
  height: 180px;
}
#vlocity .datepicker.dropdown-menu tbody button {
  padding: 6px;
}
#vlocity .datepicker.dropdown-menu.datepicker-mode-1 tbody button,
#vlocity .datepicker.dropdown-menu.datepicker-mode-2 tbody button {
  height: 65px;
}
#vlocity i.fa.fa-caret-left {
margin-right: 5px;
font-size: 13px;
}
td > #vlocity {
margin-top: 14px;
}
#vlocity > hr {
margin-top: 11px;
margin-bottom: 11px;
border: 0;
border-top: 1px solid #eee;
}

#vlocity button.vlc-next,
#vlocity button.vlc-submit,
#vlocity button.vlc-abs-submit {
background: -moz-linear-gradient(top,  #18acdd 0%, #0088dd 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#18acdd), color-stop(100%,#0088dd)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #18acdd 0%,#0088dd 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #18acdd 0%,#0088dd 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #18acdd 0%,#0088dd 100%); /* IE10+ */
background: linear-gradient(to bottom,  #18acdd 0%,#0088dd 100%); /* W3C */
padding: 8px 46px;
color: #fff;
border: 1px solid #008ab3;
font-weight: normal;
}

#vlocity button.vlc-previous,
#vlocity button.vlc-back {
background: -moz-linear-gradient(top,  #ffffff 0%, #f7f7f7 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#f7f7f7)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #ffffff 0%,#f7f7f7 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #ffffff 0%,#f7f7f7 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #ffffff 0%,#f7f7f7 100%); /* IE10+ */
background: linear-gradient(to bottom,  #ffffff 0%,#f7f7f7 100%); /* W3C */
padding: 8px 46px;
border: 1px solid rgba(0,0,0,.15);
font-weight: normal;
color: #008ab3;
}

#vlocity button.vlc-cancel{
border: none;
background-color: transparent;
color: #008ab3;
box-shadow: none;
width: auto;
font-weight: normal;
}

#vlocity button.vlc-cancel:hover {
text-decoration: underline;
cursor: pointer;
}

#vlocity .form-control[disabled], #vlocity .form-control[readonly],#vlocity fieldset[disabled] .form-control {
cursor: not-allowed;
background: #e5e5e5 !important;
opacity: 1;
color: rgba(0,0,0,.35);
border: none;
}

#vlocity div.vlc-next {
float: right !important;
}

#vlocity button:hover { cursor:pointer !important} 

#vlocity button {
line-height: 10px !important;
}

#vlocity div.vlc-abs-submit {
bottom: 15px;
right: 10px !important;
position: absolute !important;
float: right !important;
}

#vlocity .panel-title > a {
padding: 3px 10px 7px 25px;
display: block;
text-decoration: none !important;
color: white !important;
}

#vlocity .panel-default > .panel-heading {
padding: 0px;
border-top-left-radius: 3px;
border-top-right-radius: 3px;
border-bottom: none !important;
}

#vlocity button.vlc-cancel {
float: right;
border: none;
background-color: transparent;
color: #008ab3;
box-shadow: none;
width: auto;
font-weight: normal;
padding: 10px 15px;
}

#vlocity div.vlc-cancel {
float: right;
width: 100%;
}

#vlocity .panel-body {
position: relative;
}

#vlocity .vlc-header {
margin-bottom: 25px;
padding-left: 1rpx;
}  

#vlocity h1 {
font-size: 22px;
}  
                
#vlocity .vlc-disclosure {
margin-top: 0px;
background-color: #EFEFEF;
width: 100%;
}

#vlocity .vlc-textblock {
color: rgba(0,0,0,.65);
}
        
#vlocity .well-lg hr {
margin-top: 10px;
margin-bottom: 10px;
border: 0;
border-top: 1px solid transparent;
}